-- =============================================================================
-- Space.AllowParentAssignees & SpaceType.DefaultAllowParentAssignees
--
-- Controls whether participants in a child space may assign people seated on
-- ancestor spaces whose membership reaches this space.
-- On by default; only staff may edit Space.AllowParentAssignees.
-- =============================================================================

-- Developer and Integration execution grants and permissions on Row Level Security Filters
-- so that mj sync push can push RLS metadata on fresh database instances.
GRANT SELECT  ON [${mjSchema}].[vwRowLevelSecurityFilters]     TO [cdp_Developer], [cdp_Integration];
GO
GRANT EXECUTE ON [${mjSchema}].[spCreateRowLevelSecurityFilter] TO [cdp_Developer], [cdp_Integration];
GO
GRANT EXECUTE ON [${mjSchema}].[spUpdateRowLevelSecurityFilter] TO [cdp_Developer], [cdp_Integration];
GO
GRANT EXECUTE ON [${mjSchema}].[spDeleteRowLevelSecurityFilter] TO [cdp_Developer], [cdp_Integration];
GO

UPDATE [${mjSchema}].[EntityPermission]
SET CanCreate = 1, CanUpdate = 1
WHERE EntityID = (SELECT ID FROM [${mjSchema}].[Entity] WHERE Name = 'MJ: Row Level Security Filters')
  AND RoleID IN (SELECT ID FROM [${mjSchema}].[Role] WHERE Name IN ('Developer', 'Integration'));
GO

-- 1. Space.AllowParentAssignees column
IF COL_LENGTH('${flyway:defaultSchema}.Space', 'AllowParentAssignees') IS NULL
    ALTER TABLE [${flyway:defaultSchema}].[Space]
        ADD [AllowParentAssignees] BIT NOT NULL CONSTRAINT DF_Space_AllowParentAssignees DEFAULT (1);
GO

EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'1 if participants in this space may assign people seated on ancestor spaces whose membership reaches this space; 0 to restrict assignment to seats in this space or below. Only staff may change this switch.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}',
    @level1type = N'TABLE', @level1name = N'Space',
    @level2type = N'COLUMN', @level2name = N'AllowParentAssignees';
GO

-- 2. SpaceType.DefaultAllowParentAssignees column
IF COL_LENGTH('${flyway:defaultSchema}.SpaceType', 'DefaultAllowParentAssignees') IS NULL
    ALTER TABLE [${flyway:defaultSchema}].[SpaceType]
        ADD [DefaultAllowParentAssignees] BIT NOT NULL CONSTRAINT DF_SpaceType_DefaultAllowParentAssignees DEFAULT (1);
GO

EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Default AllowParentAssignees setting for new spaces of this type.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}',
    @level1type = N'TABLE', @level1name = N'SpaceType',
    @level2type = N'COLUMN', @level2name = N'DefaultAllowParentAssignees';
GO

















































-- =============================================================================
-- GENERATED BY MemberJunction CodeGen — DO NOT EDIT BY HAND
-- =============================================================================

/* SQL text to update existing entities from schema */
EXEC [${mjSchema}].[spUpdateExistingEntitiesFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';
GO

/* Insert EntityField for Space.AllowParentAssignees */
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '60473939-f7f8-4229-bd85-bb3c139eb2aa' OR (EntityID = '3648DC35-1DC4-4ED6-A1A6-5D87271A54DB' AND Name = 'AllowParentAssignees')) BEGIN
   INSERT INTO [${mjSchema}].[EntityField]
   (
      [ID],
      [EntityID],
      [Sequence],
      [Name],
      [DisplayName],
      [Description],
      [Type],
      [Length],
      [Precision],
      [Scale],
      [AllowsNull],
      [DefaultValue],
      [AutoIncrement],
      [AllowUpdateAPI],
      [IsVirtual],
      [IsComputed],
      [RelatedEntityID],
      [RelatedEntityFieldName],
      [IsNameField],
      [IncludeInUserSearchAPI],
      [IncludeRelatedEntityNameFieldInBaseView],
      [DefaultInView],
      [IsPrimaryKey],
      [IsUnique],
      [RelatedEntityDisplayType],
      [__mj_CreatedAt],
      [__mj_UpdatedAt]
   )
   VALUES
   (
      '60473939-f7f8-4229-bd85-bb3c139eb2aa',
      '3648DC35-1DC4-4ED6-A1A6-5D87271A54DB', -- Entity: MJ_BizApps_Collaboration: Spaces
      (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '3648DC35-1DC4-4ED6-A1A6-5D87271A54DB'),
      'AllowParentAssignees',
      'Allow Parent Assignees',
      '1 if participants in this space may assign people seated on ancestor spaces whose membership reaches this space; 0 to restrict assignment to seats in this space or below. Only staff may change this switch.',
      'bit',
      1,
      1,
      0,
      0,
      '(1)',
      0,
      1,
      0,
      0,
      NULL,
      NULL,
      0,
      0,
      0,
      0,
      0,
      0,
      'Search',
      GETUTCDATE(),
      GETUTCDATE()
   )
END;
GO

/* Insert EntityField for SpaceType.DefaultAllowParentAssignees */
IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '99115b9c-2f45-4b34-904b-0f1967d2aa9b' OR (EntityID = '01596359-EC4B-449C-BA16-316DE4B92A4E' AND Name = 'DefaultAllowParentAssignees')) BEGIN
   INSERT INTO [${mjSchema}].[EntityField]
   (
      [ID],
      [EntityID],
      [Sequence],
      [Name],
      [DisplayName],
      [Description],
      [Type],
      [Length],
      [Precision],
      [Scale],
      [AllowsNull],
      [DefaultValue],
      [AutoIncrement],
      [AllowUpdateAPI],
      [IsVirtual],
      [IsComputed],
      [RelatedEntityID],
      [RelatedEntityFieldName],
      [IsNameField],
      [IncludeInUserSearchAPI],
      [IncludeRelatedEntityNameFieldInBaseView],
      [DefaultInView],
      [IsPrimaryKey],
      [IsUnique],
      [RelatedEntityDisplayType],
      [__mj_CreatedAt],
      [__mj_UpdatedAt]
   )
   VALUES
   (
      '99115b9c-2f45-4b34-904b-0f1967d2aa9b',
      '01596359-EC4B-449C-BA16-316DE4B92A4E', -- Entity: MJ_BizApps_Collaboration: Space Types
      (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '01596359-EC4B-449C-BA16-316DE4B92A4E'),
      'DefaultAllowParentAssignees',
      'Default Allow Parent Assignees',
      'Default AllowParentAssignees setting for new spaces of this type.',
      'bit',
      1,
      1,
      0,
      0,
      '(1)',
      0,
      1,
      0,
      0,
      NULL,
      NULL,
      0,
      0,
      0,
      0,
      0,
      0,
      'Search',
      GETUTCDATE(),
      GETUTCDATE()
   )
END;
GO

-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Spaces
-- Item: fnSpaceParentID_GetRootID
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
------------------------------------------------------------
----- ROOT ID FUNCTION FOR: [Space].[ParentID]
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[fnSpaceParentID_GetRootID]', 'IF') IS NOT NULL
    DROP FUNCTION [${flyway:defaultSchema}].[fnSpaceParentID_GetRootID];
GO

CREATE FUNCTION [${flyway:defaultSchema}].[fnSpaceParentID_GetRootID]
(
    @RecordID uniqueidentifier,
    @ParentID uniqueidentifier
)
RETURNS TABLE
AS
RETURN
(
    WITH CTE_RootParent AS (
        SELECT
            [ID],
            [ParentID],
            [ID] AS [RootParentID],
            0 AS [Depth]
        FROM
            [${flyway:defaultSchema}].[Space]
        WHERE
            [ID] = COALESCE(@ParentID, @RecordID)

        UNION ALL

        SELECT
            c.[ID],
            c.[ParentID],
            c.[ID] AS [RootParentID],
            p.[Depth] + 1 AS [Depth]
        FROM
            [${flyway:defaultSchema}].[Space] c
        INNER JOIN
            CTE_RootParent p ON c.[ID] = p.[ParentID]
        WHERE
            p.[Depth] < 100
    )
    SELECT TOP 1
        [RootParentID] AS RootID
    FROM
        CTE_RootParent
    WHERE
        [ParentID] IS NULL
    ORDER BY
        [RootParentID]
);
GO

-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Spaces
-- Item: vwSpaces
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Collaboration: Spaces
-----               SCHEMA:      __mj_BizAppsCollaboration
-----               BASE TABLE:  Space
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwSpaces]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwSpaces];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwSpaces]
AS
SELECT
    s.*,
    mjBizAppsCollaborationSpaceType_SpaceTypeID.[Name] AS [SpaceType],
    mjBizAppsCollaborationSpace_ParentID.[Name] AS [Parent],
    MJUser_OwnerID.[Name] AS [Owner],
    root_ParentID.RootID AS [RootParentID]
FROM
    [${flyway:defaultSchema}].[Space] AS s
INNER JOIN
    [${flyway:defaultSchema}].[SpaceType] AS mjBizAppsCollaborationSpaceType_SpaceTypeID
  ON
    [s].[SpaceTypeID] = mjBizAppsCollaborationSpaceType_SpaceTypeID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[Space] AS mjBizAppsCollaborationSpace_ParentID
  ON
    [s].[ParentID] = mjBizAppsCollaborationSpace_ParentID.[ID]
INNER JOIN
    [${mjSchema}].[User] AS MJUser_OwnerID
  ON
    [s].[OwnerID] = MJUser_OwnerID.[ID]
OUTER APPLY
    [${flyway:defaultSchema}].[fnSpaceParentID_GetRootID]([s].[ID], [s].[ParentID]) AS root_ParentID
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwSpaces] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
GO

-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Space Types
-- Item: vwSpaceTypes
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Collaboration: Space Types
-----               SCHEMA:      __mj_BizAppsCollaboration
-----               BASE TABLE:  SpaceType
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwSpaceTypes]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwSpaceTypes];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwSpaceTypes]
AS
SELECT
    s.*
FROM
    [${flyway:defaultSchema}].[SpaceType] AS s
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwSpaceTypes] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
GO

-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Spaces
-- Item: spCreateSpace
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR Space
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateSpace]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateSpace];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateSpace]
    @ID uniqueidentifier = NULL,
    @SpaceTypeID uniqueidentifier,
    @ParentID_Clear bit = 0,
    @ParentID uniqueidentifier = NULL,
    @Name nvarchar(200),
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @OwnerID uniqueidentifier,
    @InheritsMembership bit = NULL,
    @AgentRetrieval nvarchar(30) = NULL,
    @StartedAt_Clear bit = 0,
    @StartedAt datetimeoffset = NULL,
    @ClosedAt_Clear bit = 0,
    @ClosedAt datetimeoffset = NULL,
    @Retention_Clear bit = 0,
    @Retention nvarchar(20) = NULL,
    @AllowParentAssignees bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[Space]
            (
                [ID],
                [SpaceTypeID],
                [ParentID],
                [Name],
                [Description],
                [OwnerID],
                [InheritsMembership],
                [AgentRetrieval],
                [StartedAt],
                [ClosedAt],
                [Retention],
                [AllowParentAssignees]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @SpaceTypeID,
                CASE WHEN @ParentID_Clear = 1 THEN NULL ELSE ISNULL(@ParentID, NULL) END,
                @Name,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @OwnerID,
                ISNULL(@InheritsMembership, 1),
                ISNULL(@AgentRetrieval, 'Included'),
                CASE WHEN @StartedAt_Clear = 1 THEN NULL ELSE ISNULL(@StartedAt, NULL) END,
                CASE WHEN @ClosedAt_Clear = 1 THEN NULL ELSE ISNULL(@ClosedAt, NULL) END,
                CASE WHEN @Retention_Clear = 1 THEN NULL ELSE ISNULL(@Retention, NULL) END,
                ISNULL(@AllowParentAssignees, 1)
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[Space]
            (
                [SpaceTypeID],
                [ParentID],
                [Name],
                [Description],
                [OwnerID],
                [InheritsMembership],
                [AgentRetrieval],
                [StartedAt],
                [ClosedAt],
                [Retention],
                [AllowParentAssignees]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @SpaceTypeID,
                CASE WHEN @ParentID_Clear = 1 THEN NULL ELSE ISNULL(@ParentID, NULL) END,
                @Name,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @OwnerID,
                ISNULL(@InheritsMembership, 1),
                ISNULL(@AgentRetrieval, 'Included'),
                CASE WHEN @StartedAt_Clear = 1 THEN NULL ELSE ISNULL(@StartedAt, NULL) END,
                CASE WHEN @ClosedAt_Clear = 1 THEN NULL ELSE ISNULL(@ClosedAt, NULL) END,
                CASE WHEN @Retention_Clear = 1 THEN NULL ELSE ISNULL(@Retention, NULL) END,
                ISNULL(@AllowParentAssignees, 1)
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwSpaces] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
GO

-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Spaces
-- Item: spUpdateSpace
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR Space
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateSpace]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateSpace];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateSpace]
    @ID uniqueidentifier,
    @SpaceTypeID uniqueidentifier = NULL,
    @ParentID_Clear bit = 0,
    @ParentID uniqueidentifier = NULL,
    @Name nvarchar(200) = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @OwnerID uniqueidentifier = NULL,
    @InheritsMembership bit = NULL,
    @AgentRetrieval nvarchar(30) = NULL,
    @StartedAt_Clear bit = 0,
    @StartedAt datetimeoffset = NULL,
    @ClosedAt_Clear bit = 0,
    @ClosedAt datetimeoffset = NULL,
    @Retention_Clear bit = 0,
    @Retention nvarchar(20) = NULL,
    @AllowParentAssignees bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Space]
    SET
        [SpaceTypeID] = ISNULL(@SpaceTypeID, [SpaceTypeID]),
        [ParentID] = CASE WHEN @ParentID_Clear = 1 THEN NULL ELSE ISNULL(@ParentID, [ParentID]) END,
        [Name] = ISNULL(@Name, [Name]),
        [Description] = CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, [Description]) END,
        [OwnerID] = ISNULL(@OwnerID, [OwnerID]),
        [InheritsMembership] = ISNULL(@InheritsMembership, [InheritsMembership]),
        [AgentRetrieval] = ISNULL(@AgentRetrieval, [AgentRetrieval]),
        [StartedAt] = CASE WHEN @StartedAt_Clear = 1 THEN NULL ELSE ISNULL(@StartedAt, [StartedAt]) END,
        [ClosedAt] = CASE WHEN @ClosedAt_Clear = 1 THEN NULL ELSE ISNULL(@ClosedAt, [ClosedAt]) END,
        [Retention] = CASE WHEN @Retention_Clear = 1 THEN NULL ELSE ISNULL(@Retention, [Retention]) END,
        [AllowParentAssignees] = ISNULL(@AllowParentAssignees, [AllowParentAssignees])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwSpaces] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwSpaces]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpace] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the Space table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateSpace]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateSpace];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateSpace
ON [${flyway:defaultSchema}].[Space]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Space]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[Space] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
GO

-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Space Types
-- Item: spCreateSpaceType
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR SpaceType
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateSpaceType]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateSpaceType];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateSpaceType]
    @ID uniqueidentifier = NULL,
    @Code nvarchar(40),
    @Name nvarchar(200),
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @Vocabulary nvarchar(50),
    @Discoverability nvarchar(20) = NULL,
    @JoinMode nvarchar(20) = NULL,
    @MessagingPanel bit = NULL,
    @LibraryPanel bit = NULL,
    @WorkPanel bit = NULL,
    @GovernancePanel bit = NULL,
    @DefaultRetention nvarchar(20) = NULL,
    @DefaultAgentRetrieval nvarchar(30) = NULL,
    @DefaultBand nvarchar(20) = NULL,
    @InviteApproval nvarchar(20) = NULL,
    @MemberCap_Clear bit = 0,
    @MemberCap int = NULL,
    @DisplayRank int = NULL,
    @IsActive bit = NULL,
    @DefaultAllowParentAssignees bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[SpaceType]
            (
                [ID],
                [Code],
                [Name],
                [Description],
                [Vocabulary],
                [Discoverability],
                [JoinMode],
                [MessagingPanel],
                [LibraryPanel],
                [WorkPanel],
                [GovernancePanel],
                [DefaultRetention],
                [DefaultAgentRetrieval],
                [DefaultBand],
                [InviteApproval],
                [MemberCap],
                [DisplayRank],
                [IsActive],
                [DefaultAllowParentAssignees]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @Code,
                @Name,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @Vocabulary,
                ISNULL(@Discoverability, 'Hidden'),
                ISNULL(@JoinMode, 'InviteOnly'),
                ISNULL(@MessagingPanel, 1),
                ISNULL(@LibraryPanel, 0),
                ISNULL(@WorkPanel, 0),
                ISNULL(@GovernancePanel, 0),
                ISNULL(@DefaultRetention, 'Indefinite'),
                ISNULL(@DefaultAgentRetrieval, 'Included'),
                ISNULL(@DefaultBand, 'Team'),
                ISNULL(@InviteApproval, 'Approve'),
                CASE WHEN @MemberCap_Clear = 1 THEN NULL ELSE ISNULL(@MemberCap, NULL) END,
                ISNULL(@DisplayRank, 0),
                ISNULL(@IsActive, 1),
                ISNULL(@DefaultAllowParentAssignees, 1)
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[SpaceType]
            (
                [Code],
                [Name],
                [Description],
                [Vocabulary],
                [Discoverability],
                [JoinMode],
                [MessagingPanel],
                [LibraryPanel],
                [WorkPanel],
                [GovernancePanel],
                [DefaultRetention],
                [DefaultAgentRetrieval],
                [DefaultBand],
                [InviteApproval],
                [MemberCap],
                [DisplayRank],
                [IsActive],
                [DefaultAllowParentAssignees]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @Code,
                @Name,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @Vocabulary,
                ISNULL(@Discoverability, 'Hidden'),
                ISNULL(@JoinMode, 'InviteOnly'),
                ISNULL(@MessagingPanel, 1),
                ISNULL(@LibraryPanel, 0),
                ISNULL(@WorkPanel, 0),
                ISNULL(@GovernancePanel, 0),
                ISNULL(@DefaultRetention, 'Indefinite'),
                ISNULL(@DefaultAgentRetrieval, 'Included'),
                ISNULL(@DefaultBand, 'Team'),
                ISNULL(@InviteApproval, 'Approve'),
                CASE WHEN @MemberCap_Clear = 1 THEN NULL ELSE ISNULL(@MemberCap, NULL) END,
                ISNULL(@DisplayRank, 0),
                ISNULL(@IsActive, 1),
                ISNULL(@DefaultAllowParentAssignees, 1)
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwSpaceTypes] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateSpaceType] TO [cdp_Developer], [cdp_Integration]
GO

-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Space Types
-- Item: spUpdateSpaceType
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR SpaceType
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateSpaceType]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateSpaceType];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateSpaceType]
    @ID uniqueidentifier,
    @Code nvarchar(40) = NULL,
    @Name nvarchar(200) = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @Vocabulary nvarchar(50) = NULL,
    @Discoverability nvarchar(20) = NULL,
    @JoinMode nvarchar(20) = NULL,
    @MessagingPanel bit = NULL,
    @LibraryPanel bit = NULL,
    @WorkPanel bit = NULL,
    @GovernancePanel bit = NULL,
    @DefaultRetention nvarchar(20) = NULL,
    @DefaultAgentRetrieval nvarchar(30) = NULL,
    @DefaultBand nvarchar(20) = NULL,
    @InviteApproval nvarchar(20) = NULL,
    @MemberCap_Clear bit = 0,
    @MemberCap int = NULL,
    @DisplayRank int = NULL,
    @IsActive bit = NULL,
    @DefaultAllowParentAssignees bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[SpaceType]
    SET
        [Code] = ISNULL(@Code, [Code]),
        [Name] = ISNULL(@Name, [Name]),
        [Description] = CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, [Description]) END,
        [Vocabulary] = ISNULL(@Vocabulary, [Vocabulary]),
        [Discoverability] = ISNULL(@Discoverability, [Discoverability]),
        [JoinMode] = ISNULL(@JoinMode, [JoinMode]),
        [MessagingPanel] = ISNULL(@MessagingPanel, [MessagingPanel]),
        [LibraryPanel] = ISNULL(@LibraryPanel, [LibraryPanel]),
        [WorkPanel] = ISNULL(@WorkPanel, [WorkPanel]),
        [GovernancePanel] = ISNULL(@GovernancePanel, [GovernancePanel]),
        [DefaultRetention] = ISNULL(@DefaultRetention, [DefaultRetention]),
        [DefaultAgentRetrieval] = ISNULL(@DefaultAgentRetrieval, [DefaultAgentRetrieval]),
        [DefaultBand] = ISNULL(@DefaultBand, [DefaultBand]),
        [InviteApproval] = ISNULL(@InviteApproval, [InviteApproval]),
        [MemberCap] = CASE WHEN @MemberCap_Clear = 1 THEN NULL ELSE ISNULL(@MemberCap, [MemberCap]) END,
        [DisplayRank] = ISNULL(@DisplayRank, [DisplayRank]),
        [IsActive] = ISNULL(@IsActive, [IsActive]),
        [DefaultAllowParentAssignees] = ISNULL(@DefaultAllowParentAssignees, [DefaultAllowParentAssignees])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwSpaceTypes] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwSpaceTypes]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpaceType] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the SpaceType table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateSpaceType]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateSpaceType];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateSpaceType
ON [${flyway:defaultSchema}].[SpaceType]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[SpaceType]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[SpaceType] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO
GO

