-- =============================================================================
-- Migration: V202609280200__v0.1.x__Retire_Room_Kind.sql
-- Retires 'Room' kind: turns any Room row into General, drops filtered unique
-- index, and narrows SpaceChat.Kind CHECK constraint to ('General', 'Private', 'Topic').
-- =============================================================================

-- 1. Drop filtered unique index if present
IF EXISTS (
    SELECT 1 FROM sys.indexes 
    WHERE name = N'UQ_SpaceChat_SpaceID_Room' 
      AND object_id = OBJECT_ID(N'[${flyway:defaultSchema}].[SpaceChat]')
)
BEGIN
    DROP INDEX [UQ_SpaceChat_SpaceID_Room] ON [${flyway:defaultSchema}].[SpaceChat];
END
GO

-- 2. Turn existing Room rows into General
UPDATE [${flyway:defaultSchema}].[SpaceChat]
SET [Kind] = 'General'
WHERE [Kind] = 'Room';
GO

-- 3. Drop existing CHECK constraint and replace with narrowed CHECK constraint
IF EXISTS (
    SELECT 1 FROM sys.check_constraints 
    WHERE name = N'CK_SpaceChat_Kind'
      AND parent_object_id = OBJECT_ID(N'[${flyway:defaultSchema}].[SpaceChat]')
)
BEGIN
    ALTER TABLE [${flyway:defaultSchema}].[SpaceChat]
    DROP CONSTRAINT [CK_SpaceChat_Kind];
END
GO

ALTER TABLE [${flyway:defaultSchema}].[SpaceChat]
ADD CONSTRAINT [CK_SpaceChat_Kind] CHECK ([Kind] IN ('General', 'Private', 'Topic'));
GO

-- 4. Add ArchivedOnSpaceClose column to track chats archived when a space closes
IF NOT EXISTS (
    SELECT 1 FROM sys.columns 
    WHERE name = N'ArchivedOnSpaceClose' 
      AND object_id = OBJECT_ID(N'[${flyway:defaultSchema}].[SpaceChat]')
)
BEGIN
    ALTER TABLE [${flyway:defaultSchema}].[SpaceChat]
    ADD [ArchivedOnSpaceClose] BIT NOT NULL CONSTRAINT DF_SpaceChat_ArchivedOnSpaceClose DEFAULT 0;
END
GO



















































-- =============================================================================
-- GENERATED BY MemberJunction CodeGen — DO NOT EDIT BY HAND
-- =============================================================================

/* SQL text to update existing entities from schema */
EXEC [${mjSchema}].[spUpdateExistingEntitiesFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to insert 1 new entity field(s) */

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'e2f00c2e-9d8a-46db-b817-27dc913a2211' OR (EntityID = '75E3ED25-C46B-45C1-96F7-91578D88DBE2' AND Name = 'ArchivedOnSpaceClose')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'e2f00c2e-9d8a-46db-b817-27dc913a2211',
            '75E3ED25-C46B-45C1-96F7-91578D88DBE2', -- Entity: MJ_BizApps_Collaboration: Space Chats
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '75E3ED25-C46B-45C1-96F7-91578D88DBE2'),
            'ArchivedOnSpaceClose',
            'Archived On Space Close',
            NULL,
            'bit',
            1,
            1,
            0,
            0,
            '(0)',
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* SQL text to update existing entity fields from schema */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to update entity field value sequence */
UPDATE [${mjSchema}].[EntityFieldValue] SET Sequence=3 WHERE ID='D40C8FF6-EC0B-488A-9CC7-2464A132601D';

/* SQL text to sync schema info from database schemas */
EXEC [${mjSchema}].[spUpdateSchemaInfoFromDatabase] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* Index for Foreign Keys for SpaceChat */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Space Chats
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key SpaceID in table SpaceChat
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_SpaceChat_SpaceID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[SpaceChat]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_SpaceChat_SpaceID ON [${flyway:defaultSchema}].[SpaceChat] ([SpaceID]);

-- Index for foreign key ConversationID in table SpaceChat
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_SpaceChat_ConversationID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[SpaceChat]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_SpaceChat_ConversationID ON [${flyway:defaultSchema}].[SpaceChat] ([ConversationID]);

/* Base View SQL for MJ_BizApps_Collaboration: Space Chats */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Space Chats
-- Item: vwSpaceChats
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Collaboration: Space Chats
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  SpaceChat
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwSpaceChats]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwSpaceChats];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwSpaceChats]
AS
SELECT
    s.*,
    mjBizAppsCollaborationSpace_SpaceID.[Name] AS [Space],
    MJConversation_ConversationID.[Name] AS [Conversation]
FROM
    [${flyway:defaultSchema}].[SpaceChat] AS s
INNER JOIN
    [${flyway:defaultSchema}].[Space] AS mjBizAppsCollaborationSpace_SpaceID
  ON
    [s].[SpaceID] = mjBizAppsCollaborationSpace_SpaceID.[ID]
INNER JOIN
    [${mjSchema}].[Conversation] AS MJConversation_ConversationID
  ON
    [s].[ConversationID] = MJConversation_ConversationID.[ID]
GO
REVOKE SELECT ON [${flyway:defaultSchema}].[vwSpaceChats] FROM [cdp_Developer]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwSpaceChats] FROM [cdp_Integration]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwSpaceChats] FROM [cdp_UI]
GRANT SELECT ON [${flyway:defaultSchema}].[vwSpaceChats] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Collaboration: Space Chats */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Space Chats
-- Item: Permissions for vwSpaceChats
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

REVOKE SELECT ON [${flyway:defaultSchema}].[vwSpaceChats] FROM [cdp_Developer]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwSpaceChats] FROM [cdp_Integration]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwSpaceChats] FROM [cdp_UI]
GRANT SELECT ON [${flyway:defaultSchema}].[vwSpaceChats] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Collaboration: Space Chats */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Space Chats
-- Item: spCreateSpaceChat
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR SpaceChat
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateSpaceChat]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateSpaceChat];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateSpaceChat]
    @ID uniqueidentifier = NULL,
    @SpaceID uniqueidentifier,
    @ConversationID uniqueidentifier,
    @Name nvarchar(255),
    @Subject_Clear bit = 0,
    @Subject nvarchar(500) = NULL,
    @Kind nvarchar(50) = NULL,
    @Status nvarchar(50) = NULL,
    @ArchivedOnSpaceClose bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[SpaceChat]
            (
                [ID],
                [SpaceID],
                [ConversationID],
                [Name],
                [Subject],
                [Kind],
                [Status],
                [ArchivedOnSpaceClose]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @SpaceID,
                @ConversationID,
                @Name,
                CASE WHEN @Subject_Clear = 1 THEN NULL ELSE ISNULL(@Subject, NULL) END,
                ISNULL(@Kind, 'General'),
                ISNULL(@Status, 'Active'),
                ISNULL(@ArchivedOnSpaceClose, 0)
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[SpaceChat]
            (
                [SpaceID],
                [ConversationID],
                [Name],
                [Subject],
                [Kind],
                [Status],
                [ArchivedOnSpaceClose]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @SpaceID,
                @ConversationID,
                @Name,
                CASE WHEN @Subject_Clear = 1 THEN NULL ELSE ISNULL(@Subject, NULL) END,
                ISNULL(@Kind, 'General'),
                ISNULL(@Status, 'Active'),
                ISNULL(@ArchivedOnSpaceClose, 0)
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwSpaceChats] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpaceChat] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpaceChat] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateSpaceChat] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Collaboration: Space Chats */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpaceChat] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpaceChat] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateSpaceChat] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Collaboration: Space Chats */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Space Chats
-- Item: spUpdateSpaceChat
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR SpaceChat
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateSpaceChat]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateSpaceChat];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateSpaceChat]
    @ID uniqueidentifier,
    @SpaceID uniqueidentifier = NULL,
    @ConversationID uniqueidentifier = NULL,
    @Name nvarchar(255) = NULL,
    @Subject_Clear bit = 0,
    @Subject nvarchar(500) = NULL,
    @Kind nvarchar(50) = NULL,
    @Status nvarchar(50) = NULL,
    @ArchivedOnSpaceClose bit = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[SpaceChat]
    SET
        [SpaceID] = ISNULL(@SpaceID, [SpaceID]),
        [ConversationID] = ISNULL(@ConversationID, [ConversationID]),
        [Name] = ISNULL(@Name, [Name]),
        [Subject] = CASE WHEN @Subject_Clear = 1 THEN NULL ELSE ISNULL(@Subject, [Subject]) END,
        [Kind] = ISNULL(@Kind, [Kind]),
        [Status] = ISNULL(@Status, [Status]),
        [ArchivedOnSpaceClose] = ISNULL(@ArchivedOnSpaceClose, [ArchivedOnSpaceClose])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwSpaceChats] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwSpaceChats]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpaceChat] FROM [cdp_Integration]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpaceChat] FROM [cdp_Developer]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpaceChat] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the SpaceChat table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateSpaceChat]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateSpaceChat];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateSpaceChat
ON [${flyway:defaultSchema}].[SpaceChat]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[SpaceChat]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[SpaceChat] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Collaboration: Space Chats */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpaceChat] FROM [cdp_Integration]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpaceChat] FROM [cdp_Developer]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpaceChat] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Collaboration: Space Chats */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Space Chats
-- Item: spDeleteSpaceChat
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR SpaceChat
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteSpaceChat]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteSpaceChat];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteSpaceChat]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[SpaceChat]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteSpaceChat] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteSpaceChat] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteSpaceChat] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Collaboration: Space Chats */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteSpaceChat] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteSpaceChat] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteSpaceChat] TO [cdp_Developer], [cdp_Integration];

/* SQL text to delete unneeded entity fields (1 scoped entities) */
EXEC [${mjSchema}].[spDeleteUnneededEntityFields] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @EntityIDs='75E3ED25-C46B-45C1-96F7-91578D88DBE2', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to update existing entity fields from schema (1 scoped entities) */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @EntityIDs='75E3ED25-C46B-45C1-96F7-91578D88DBE2', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';
