-- =============================================================================
-- Space.IconClass, Space.Color & Space.BackgroundImageURL
--
-- Space distinctiveness:
-- Allows spaces to have custom visual tile glyphs, brand colors, and optional
-- hero/backdrop images (with fallback to SpaceType defaults if null).
-- =============================================================================

-- 1. Space.IconClass
IF COL_LENGTH('${flyway:defaultSchema}.Space', 'IconClass') IS NULL
    ALTER TABLE [${flyway:defaultSchema}].[Space]
        ADD [IconClass] NVARCHAR(100) NULL;
GO

EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Font Awesome icon class representing the space (e.g., fa-solid fa-folder-tree, fa-solid fa-briefcase). Overrides SpaceType.IconClass if set.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}',
    @level1type = N'TABLE', @level1name = N'Space',
    @level2type = N'COLUMN', @level2name = N'IconClass';
GO

-- 2. Space.Color
IF COL_LENGTH('${flyway:defaultSchema}.Space', 'Color') IS NULL
    ALTER TABLE [${flyway:defaultSchema}].[Space]
        ADD [Color] NVARCHAR(50) NULL;
GO

EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Hex color code representing the space (e.g., #0076b6, #10b981). Overrides SpaceType.Color if set.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}',
    @level1type = N'TABLE', @level1name = N'Space',
    @level2type = N'COLUMN', @level2name = N'Color';
GO

-- 3. Space.BackgroundImageURL
IF COL_LENGTH('${flyway:defaultSchema}.Space', 'BackgroundImageURL') IS NULL
    ALTER TABLE [${flyway:defaultSchema}].[Space]
        ADD [BackgroundImageURL] NVARCHAR(1000) NULL;
GO

EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'URL of an optional hero banner or background image displayed in the space header and overview.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}',
    @level1type = N'TABLE', @level1name = N'Space',
    @level2type = N'COLUMN', @level2name = N'BackgroundImageURL';
GO




















































-- =============================================================================
-- GENERATED BY MemberJunction CodeGen — DO NOT EDIT BY HAND
-- =============================================================================
/* SQL text to update existing entities from schema */
EXEC [${mjSchema}].[spUpdateExistingEntitiesFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to insert 3 new entity field(s) */

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'd826ef6d-6a39-42b9-814f-b69bd5d085b9' OR (EntityID = '3648DC35-1DC4-4ED6-A1A6-5D87271A54DB' AND Name = 'IconClass')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'd826ef6d-6a39-42b9-814f-b69bd5d085b9',
            '3648DC35-1DC4-4ED6-A1A6-5D87271A54DB', -- Entity: MJ_BizApps_Collaboration: Spaces
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '3648DC35-1DC4-4ED6-A1A6-5D87271A54DB'),
            'IconClass',
            'Icon Class',
            NULL,
            'nvarchar',
            200,
            0,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '9dccc224-4bfc-4241-b6bf-f11d2083024b' OR (EntityID = '3648DC35-1DC4-4ED6-A1A6-5D87271A54DB' AND Name = 'Color')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '9dccc224-4bfc-4241-b6bf-f11d2083024b',
            '3648DC35-1DC4-4ED6-A1A6-5D87271A54DB', -- Entity: MJ_BizApps_Collaboration: Spaces
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '3648DC35-1DC4-4ED6-A1A6-5D87271A54DB'),
            'Color',
            'Color',
            NULL,
            'nvarchar',
            100,
            0,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '8b513405-1966-4719-b1c3-ce08fa87bf21' OR (EntityID = '3648DC35-1DC4-4ED6-A1A6-5D87271A54DB' AND Name = 'BackgroundImageURL')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '8b513405-1966-4719-b1c3-ce08fa87bf21',
            '3648DC35-1DC4-4ED6-A1A6-5D87271A54DB', -- Entity: MJ_BizApps_Collaboration: Spaces
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '3648DC35-1DC4-4ED6-A1A6-5D87271A54DB'),
            'BackgroundImageURL',
            'Background Image URL',
            NULL,
            'nvarchar',
            2000,
            0,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* SQL text to update existing entity fields from schema */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to sync schema info from database schemas */
EXEC [${mjSchema}].[spUpdateSchemaInfoFromDatabase] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* Index for Foreign Keys for Space */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Spaces
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key SpaceTypeID in table Space
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Space_SpaceTypeID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Space]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Space_SpaceTypeID ON [${flyway:defaultSchema}].[Space] ([SpaceTypeID]);

-- Index for foreign key ParentID in table Space
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Space_ParentID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Space]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Space_ParentID ON [${flyway:defaultSchema}].[Space] ([ParentID]);

-- Index for foreign key OwnerID in table Space
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_Space_OwnerID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[Space]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_Space_OwnerID ON [${flyway:defaultSchema}].[Space] ([OwnerID]);

/* Base View SQL for MJ_BizApps_Collaboration: Spaces */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Spaces
-- Item: vwSpaces
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Collaboration: Spaces
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  Space
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwSpaces]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwSpaces];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwSpaces]
AS
SELECT
    s.*,
    mjBizAppsCollaborationSpaceType_SpaceTypeID.[Name] AS [SpaceType],
    mjBizAppsCollaborationSpace_ParentID.[Name] AS [Parent],
    MJUser_OwnerID.[Name] AS [Owner]
FROM
    [${flyway:defaultSchema}].[Space] AS s
INNER JOIN
    [${flyway:defaultSchema}].[SpaceType] AS mjBizAppsCollaborationSpaceType_SpaceTypeID
  ON
    [s].[SpaceTypeID] = mjBizAppsCollaborationSpaceType_SpaceTypeID.[ID]
LEFT OUTER JOIN
    [${flyway:defaultSchema}].[Space] AS mjBizAppsCollaborationSpace_ParentID
  ON
    [s].[ParentID] = mjBizAppsCollaborationSpace_ParentID.[ID]
INNER JOIN
    [${mjSchema}].[User] AS MJUser_OwnerID
  ON
    [s].[OwnerID] = MJUser_OwnerID.[ID]
GO
REVOKE SELECT ON [${flyway:defaultSchema}].[vwSpaces] FROM [cdp_UI]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwSpaces] FROM [cdp_Developer]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwSpaces] FROM [cdp_Integration]
GRANT SELECT ON [${flyway:defaultSchema}].[vwSpaces] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Collaboration: Spaces */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Spaces
-- Item: Permissions for vwSpaces
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

REVOKE SELECT ON [${flyway:defaultSchema}].[vwSpaces] FROM [cdp_UI]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwSpaces] FROM [cdp_Developer]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwSpaces] FROM [cdp_Integration]
GRANT SELECT ON [${flyway:defaultSchema}].[vwSpaces] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Collaboration: Spaces */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Spaces
-- Item: spCreateSpace
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR Space
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateSpace]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateSpace];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateSpace]
    @ID uniqueidentifier = NULL,
    @SpaceTypeID uniqueidentifier,
    @ParentID_Clear bit = 0,
    @ParentID uniqueidentifier = NULL,
    @Name nvarchar(200),
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @OwnerID uniqueidentifier,
    @InheritsMembership bit = NULL,
    @AgentRetrieval nvarchar(30) = NULL,
    @StartedAt_Clear bit = 0,
    @StartedAt datetimeoffset = NULL,
    @ClosedAt_Clear bit = 0,
    @ClosedAt datetimeoffset = NULL,
    @Retention_Clear bit = 0,
    @Retention nvarchar(20) = NULL,
    @AllowParentAssignees bit = NULL,
    @PlannedCloseAt_Clear bit = 0,
    @PlannedCloseAt datetimeoffset = NULL,
    @IconClass_Clear bit = 0,
    @IconClass nvarchar(100) = NULL,
    @Color_Clear bit = 0,
    @Color nvarchar(50) = NULL,
    @BackgroundImageURL_Clear bit = 0,
    @BackgroundImageURL nvarchar(1000) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[Space]
            (
                [ID],
                [SpaceTypeID],
                [ParentID],
                [Name],
                [Description],
                [OwnerID],
                [InheritsMembership],
                [AgentRetrieval],
                [StartedAt],
                [ClosedAt],
                [Retention],
                [AllowParentAssignees],
                [PlannedCloseAt],
                [IconClass],
                [Color],
                [BackgroundImageURL]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @SpaceTypeID,
                CASE WHEN @ParentID_Clear = 1 THEN NULL ELSE ISNULL(@ParentID, NULL) END,
                @Name,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @OwnerID,
                ISNULL(@InheritsMembership, 1),
                ISNULL(@AgentRetrieval, 'Included'),
                CASE WHEN @StartedAt_Clear = 1 THEN NULL ELSE ISNULL(@StartedAt, NULL) END,
                CASE WHEN @ClosedAt_Clear = 1 THEN NULL ELSE ISNULL(@ClosedAt, NULL) END,
                CASE WHEN @Retention_Clear = 1 THEN NULL ELSE ISNULL(@Retention, NULL) END,
                ISNULL(@AllowParentAssignees, 1),
                CASE WHEN @PlannedCloseAt_Clear = 1 THEN NULL ELSE ISNULL(@PlannedCloseAt, NULL) END,
                CASE WHEN @IconClass_Clear = 1 THEN NULL ELSE ISNULL(@IconClass, NULL) END,
                CASE WHEN @Color_Clear = 1 THEN NULL ELSE ISNULL(@Color, NULL) END,
                CASE WHEN @BackgroundImageURL_Clear = 1 THEN NULL ELSE ISNULL(@BackgroundImageURL, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[Space]
            (
                [SpaceTypeID],
                [ParentID],
                [Name],
                [Description],
                [OwnerID],
                [InheritsMembership],
                [AgentRetrieval],
                [StartedAt],
                [ClosedAt],
                [Retention],
                [AllowParentAssignees],
                [PlannedCloseAt],
                [IconClass],
                [Color],
                [BackgroundImageURL]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @SpaceTypeID,
                CASE WHEN @ParentID_Clear = 1 THEN NULL ELSE ISNULL(@ParentID, NULL) END,
                @Name,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @OwnerID,
                ISNULL(@InheritsMembership, 1),
                ISNULL(@AgentRetrieval, 'Included'),
                CASE WHEN @StartedAt_Clear = 1 THEN NULL ELSE ISNULL(@StartedAt, NULL) END,
                CASE WHEN @ClosedAt_Clear = 1 THEN NULL ELSE ISNULL(@ClosedAt, NULL) END,
                CASE WHEN @Retention_Clear = 1 THEN NULL ELSE ISNULL(@Retention, NULL) END,
                ISNULL(@AllowParentAssignees, 1),
                CASE WHEN @PlannedCloseAt_Clear = 1 THEN NULL ELSE ISNULL(@PlannedCloseAt, NULL) END,
                CASE WHEN @IconClass_Clear = 1 THEN NULL ELSE ISNULL(@IconClass, NULL) END,
                CASE WHEN @Color_Clear = 1 THEN NULL ELSE ISNULL(@Color, NULL) END,
                CASE WHEN @BackgroundImageURL_Clear = 1 THEN NULL ELSE ISNULL(@BackgroundImageURL, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwSpaces] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] FROM [cdp_Integration]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] FROM [cdp_UI]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Collaboration: Spaces */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] FROM [cdp_Integration]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] FROM [cdp_UI]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Collaboration: Spaces */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Spaces
-- Item: spUpdateSpace
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR Space
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateSpace]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateSpace];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateSpace]
    @ID uniqueidentifier,
    @SpaceTypeID uniqueidentifier = NULL,
    @ParentID_Clear bit = 0,
    @ParentID uniqueidentifier = NULL,
    @Name nvarchar(200) = NULL,
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @OwnerID uniqueidentifier = NULL,
    @InheritsMembership bit = NULL,
    @AgentRetrieval nvarchar(30) = NULL,
    @StartedAt_Clear bit = 0,
    @StartedAt datetimeoffset = NULL,
    @ClosedAt_Clear bit = 0,
    @ClosedAt datetimeoffset = NULL,
    @Retention_Clear bit = 0,
    @Retention nvarchar(20) = NULL,
    @AllowParentAssignees bit = NULL,
    @PlannedCloseAt_Clear bit = 0,
    @PlannedCloseAt datetimeoffset = NULL,
    @IconClass_Clear bit = 0,
    @IconClass nvarchar(100) = NULL,
    @Color_Clear bit = 0,
    @Color nvarchar(50) = NULL,
    @BackgroundImageURL_Clear bit = 0,
    @BackgroundImageURL nvarchar(1000) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Space]
    SET
        [SpaceTypeID] = ISNULL(@SpaceTypeID, [SpaceTypeID]),
        [ParentID] = CASE WHEN @ParentID_Clear = 1 THEN NULL ELSE ISNULL(@ParentID, [ParentID]) END,
        [Name] = ISNULL(@Name, [Name]),
        [Description] = CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, [Description]) END,
        [OwnerID] = ISNULL(@OwnerID, [OwnerID]),
        [InheritsMembership] = ISNULL(@InheritsMembership, [InheritsMembership]),
        [AgentRetrieval] = ISNULL(@AgentRetrieval, [AgentRetrieval]),
        [StartedAt] = CASE WHEN @StartedAt_Clear = 1 THEN NULL ELSE ISNULL(@StartedAt, [StartedAt]) END,
        [ClosedAt] = CASE WHEN @ClosedAt_Clear = 1 THEN NULL ELSE ISNULL(@ClosedAt, [ClosedAt]) END,
        [Retention] = CASE WHEN @Retention_Clear = 1 THEN NULL ELSE ISNULL(@Retention, [Retention]) END,
        [AllowParentAssignees] = ISNULL(@AllowParentAssignees, [AllowParentAssignees]),
        [PlannedCloseAt] = CASE WHEN @PlannedCloseAt_Clear = 1 THEN NULL ELSE ISNULL(@PlannedCloseAt, [PlannedCloseAt]) END,
        [IconClass] = CASE WHEN @IconClass_Clear = 1 THEN NULL ELSE ISNULL(@IconClass, [IconClass]) END,
        [Color] = CASE WHEN @Color_Clear = 1 THEN NULL ELSE ISNULL(@Color, [Color]) END,
        [BackgroundImageURL] = CASE WHEN @BackgroundImageURL_Clear = 1 THEN NULL ELSE ISNULL(@BackgroundImageURL, [BackgroundImageURL]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwSpaces] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwSpaces]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpace] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpace] FROM [cdp_Integration]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpace] FROM [cdp_UI]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpace] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the Space table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateSpace]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateSpace];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateSpace
ON [${flyway:defaultSchema}].[Space]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[Space]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[Space] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Collaboration: Spaces */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpace] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpace] FROM [cdp_Integration]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpace] FROM [cdp_UI]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateSpace] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Collaboration: Spaces */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration: Spaces
-- Item: spDeleteSpace
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR Space
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteSpace]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteSpace];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteSpace]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[Space]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteSpace] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteSpace] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteSpace] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Collaboration: Spaces */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteSpace] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteSpace] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteSpace] TO [cdp_Developer], [cdp_Integration];

/* SQL text to delete unneeded entity fields (1 scoped entities) */
EXEC [${mjSchema}].[spDeleteUnneededEntityFields] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @EntityIDs='3648DC35-1DC4-4ED6-A1A6-5D87271A54DB', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to update existing entity fields from schema (1 scoped entities) */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @EntityIDs='3648DC35-1DC4-4ED6-A1A6-5D87271A54DB', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';
