-- =============================================================================
-- Migration: InheritsMembership Default 0 & fnCollaborationCommonAccess Fail-Closed
-- Follows Reviewer Punch List 4: Item 11 and Item 28.
-- =============================================================================

-- 1. Space.InheritsMembership default to 0
DECLARE @dfName sysname;
SELECT @dfName = dc.name
FROM sys.default_constraints dc
INNER JOIN sys.columns c ON c.default_object_id = dc.object_id
WHERE dc.parent_object_id = OBJECT_ID(N'${flyway:defaultSchema}.Space')
  AND c.name = N'InheritsMembership';

IF @dfName IS NOT NULL
BEGIN
    EXEC(N'ALTER TABLE [${flyway:defaultSchema}].[Space] DROP CONSTRAINT [' + @dfName + N']');
END;

ALTER TABLE [${flyway:defaultSchema}].[Space]
    ADD CONSTRAINT DF_Space_InheritsMembership DEFAULT 0 FOR [InheritsMembership];
GO

-- Update EntityField DefaultValue in metadata
UPDATE [${mjSchema}].[EntityField]
SET [DefaultValue] = N'0'
WHERE [EntityID] = N'3648DC35-1DC4-4ED6-A1A6-5D87271A54DB'
  AND [Name] = N'InheritsMembership';
GO

-- 2. fnCollaborationCommonAccess: fail closed on malformed list or unknown principal
CREATE OR ALTER FUNCTION [${flyway:defaultSchema}].[fnCollaborationCommonAccess](@UserIDs NVARCHAR(MAX))
RETURNS @Common TABLE (
    SpaceID UNIQUEIDENTIFIER NOT NULL,
    CanSeeTeam BIT NOT NULL
)
AS
BEGIN
    IF @UserIDs IS NULL OR LTRIM(RTRIM(@UserIDs)) = ''
        RETURN;

    -- Fail closed if ANY token in @UserIDs is not a valid UUID
    IF EXISTS (
        SELECT 1
        FROM STRING_SPLIT(@UserIDs, ',')
        WHERE TRY_CAST(LTRIM(RTRIM(value)) AS UNIQUEIDENTIFIER) IS NULL
           OR LTRIM(RTRIM(value)) = ''
    )
        RETURN;

    DECLARE @UserCount INT;
    SELECT @UserCount = COUNT(DISTINCT CAST(LTRIM(RTRIM(value)) AS UNIQUEIDENTIFIER))
    FROM STRING_SPLIT(@UserIDs, ',');

    IF @UserCount = 0
        RETURN;

    ;WITH UserAccess AS (
        SELECT u.UserID, a.SpaceID, a.CanSeeTeam
        FROM (
            SELECT DISTINCT CAST(LTRIM(RTRIM(value)) AS UNIQUEIDENTIFIER) AS UserID
            FROM STRING_SPLIT(@UserIDs, ',')
        ) AS u
        CROSS APPLY [${flyway:defaultSchema}].[fnCollaborationAccess](u.UserID) AS a
    )
    INSERT INTO @Common (SpaceID, CanSeeTeam)
    SELECT SpaceID,
           CASE WHEN MIN(CAST(CanSeeTeam AS INT)) = 1 THEN 1 ELSE 0 END AS CanSeeTeam
    FROM UserAccess
    GROUP BY SpaceID
    HAVING COUNT(DISTINCT UserID) = @UserCount;

    RETURN;
END;
GO


















































-- =============================================================================
-- GENERATED BY MemberJunction CodeGen — DO NOT EDIT BY HAND
-- =============================================================================

IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateSpace]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateSpace];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateSpace]
    @ID uniqueidentifier = NULL,
    @SpaceTypeID uniqueidentifier,
    @ParentID_Clear bit = 0,
    @ParentID uniqueidentifier = NULL,
    @Name nvarchar(200),
    @Description_Clear bit = 0,
    @Description nvarchar(MAX) = NULL,
    @OwnerID uniqueidentifier,
    @InheritsMembership bit = NULL,
    @AgentRetrieval nvarchar(30) = NULL,
    @StartedAt_Clear bit = 0,
    @StartedAt datetimeoffset = NULL,
    @ClosedAt_Clear bit = 0,
    @ClosedAt datetimeoffset = NULL,
    @Retention_Clear bit = 0,
    @Retention nvarchar(20) = NULL,
    @AllowParentAssignees bit = NULL,
    @PlannedCloseAt_Clear bit = 0,
    @PlannedCloseAt datetimeoffset = NULL,
    @IconClass_Clear bit = 0,
    @IconClass nvarchar(100) = NULL,
    @Color_Clear bit = 0,
    @Color nvarchar(50) = NULL,
    @BackgroundImageURL_Clear bit = 0,
    @BackgroundImageURL nvarchar(1000) = NULL,
    @Configuration_Clear bit = 0,
    @Configuration nvarchar(MAX) = NULL,
    @AnchorEntityID_Clear bit = 0,
    @AnchorEntityID uniqueidentifier = NULL,
    @AnchorRecordID_Clear bit = 0,
    @AnchorRecordID nvarchar(450) = NULL,
    @PostCloseAccess_Clear bit = 0,
    @PostCloseAccess nvarchar(20) = NULL,
    @PostCloseAccessDays_Clear bit = 0,
    @PostCloseAccessDays int = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[Space]
            (
                [ID],
                [SpaceTypeID],
                [ParentID],
                [Name],
                [Description],
                [OwnerID],
                [InheritsMembership],
                [AgentRetrieval],
                [StartedAt],
                [ClosedAt],
                [Retention],
                [AllowParentAssignees],
                [PlannedCloseAt],
                [IconClass],
                [Color],
                [BackgroundImageURL],
                [Configuration],
                [AnchorEntityID],
                [AnchorRecordID],
                [PostCloseAccess],
                [PostCloseAccessDays]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @SpaceTypeID,
                CASE WHEN @ParentID_Clear = 1 THEN NULL ELSE ISNULL(@ParentID, NULL) END,
                @Name,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @OwnerID,
                ISNULL(@InheritsMembership, 0),
                ISNULL(@AgentRetrieval, 'Included'),
                CASE WHEN @StartedAt_Clear = 1 THEN NULL ELSE ISNULL(@StartedAt, NULL) END,
                CASE WHEN @ClosedAt_Clear = 1 THEN NULL ELSE ISNULL(@ClosedAt, NULL) END,
                CASE WHEN @Retention_Clear = 1 THEN NULL ELSE ISNULL(@Retention, NULL) END,
                ISNULL(@AllowParentAssignees, 1),
                CASE WHEN @PlannedCloseAt_Clear = 1 THEN NULL ELSE ISNULL(@PlannedCloseAt, NULL) END,
                CASE WHEN @IconClass_Clear = 1 THEN NULL ELSE ISNULL(@IconClass, NULL) END,
                CASE WHEN @Color_Clear = 1 THEN NULL ELSE ISNULL(@Color, NULL) END,
                CASE WHEN @BackgroundImageURL_Clear = 1 THEN NULL ELSE ISNULL(@BackgroundImageURL, NULL) END,
                CASE WHEN @Configuration_Clear = 1 THEN NULL ELSE ISNULL(@Configuration, NULL) END,
                CASE WHEN @AnchorEntityID_Clear = 1 THEN NULL ELSE ISNULL(@AnchorEntityID, NULL) END,
                CASE WHEN @AnchorRecordID_Clear = 1 THEN NULL ELSE ISNULL(@AnchorRecordID, NULL) END,
                CASE WHEN @PostCloseAccess_Clear = 1 THEN NULL ELSE ISNULL(@PostCloseAccess, NULL) END,
                CASE WHEN @PostCloseAccessDays_Clear = 1 THEN NULL ELSE ISNULL(@PostCloseAccessDays, NULL) END
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[Space]
            (
                [SpaceTypeID],
                [ParentID],
                [Name],
                [Description],
                [OwnerID],
                [InheritsMembership],
                [AgentRetrieval],
                [StartedAt],
                [ClosedAt],
                [Retention],
                [AllowParentAssignees],
                [PlannedCloseAt],
                [IconClass],
                [Color],
                [BackgroundImageURL],
                [Configuration],
                [AnchorEntityID],
                [AnchorRecordID],
                [PostCloseAccess],
                [PostCloseAccessDays]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @SpaceTypeID,
                CASE WHEN @ParentID_Clear = 1 THEN NULL ELSE ISNULL(@ParentID, NULL) END,
                @Name,
                CASE WHEN @Description_Clear = 1 THEN NULL ELSE ISNULL(@Description, NULL) END,
                @OwnerID,
                ISNULL(@InheritsMembership, 0),
                ISNULL(@AgentRetrieval, 'Included'),
                CASE WHEN @StartedAt_Clear = 1 THEN NULL ELSE ISNULL(@StartedAt, NULL) END,
                CASE WHEN @ClosedAt_Clear = 1 THEN NULL ELSE ISNULL(@ClosedAt, NULL) END,
                CASE WHEN @Retention_Clear = 1 THEN NULL ELSE ISNULL(@Retention, NULL) END,
                ISNULL(@AllowParentAssignees, 1),
                CASE WHEN @PlannedCloseAt_Clear = 1 THEN NULL ELSE ISNULL(@PlannedCloseAt, NULL) END,
                CASE WHEN @IconClass_Clear = 1 THEN NULL ELSE ISNULL(@IconClass, NULL) END,
                CASE WHEN @Color_Clear = 1 THEN NULL ELSE ISNULL(@Color, NULL) END,
                CASE WHEN @BackgroundImageURL_Clear = 1 THEN NULL ELSE ISNULL(@BackgroundImageURL, NULL) END,
                CASE WHEN @Configuration_Clear = 1 THEN NULL ELSE ISNULL(@Configuration, NULL) END,
                CASE WHEN @AnchorEntityID_Clear = 1 THEN NULL ELSE ISNULL(@AnchorEntityID, NULL) END,
                CASE WHEN @AnchorRecordID_Clear = 1 THEN NULL ELSE ISNULL(@AnchorRecordID, NULL) END,
                CASE WHEN @PostCloseAccess_Clear = 1 THEN NULL ELSE ISNULL(@PostCloseAccess, NULL) END,
                CASE WHEN @PostCloseAccessDays_Clear = 1 THEN NULL ELSE ISNULL(@PostCloseAccessDays, NULL) END
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwSpaces] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] FROM [cdp_Integration]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] FROM [cdp_UI]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateSpace] TO [cdp_UI], [cdp_Developer], [cdp_Integration];
GO
