export {
    agentMayQuote,
    authorizeItemWrite,
    authorizeSpaceWrite,
    flagExceedsGrantor,
    initialMemberStatus,
    isSelfRemoval,
    membershipReaches,
    parentCreatesCycle,
    planSpaceWrite,
    promotionStamps,
    refuseInvite,
    retentionDeadline,
    visibleSpaces,
} from './rules.js';
export type {
    AgentRetrieval,
    Band,
    InviteApproval,
    InviteRefusal,
    MemberSnapshot,
    PromotionDecision,
    Retention,
    RoleFlags,
    SpaceNode,
    InviteDecision,
} from './rules.js';
