/**
 * Example Space Types - Entities Package
 *
 * Only the subtype entity class (ExampleBoard), generated by CodeGen for the examples' own schema (an IsA child of Spaces).
 * Importing the package registers it. The server package and the client package both depend on it, and a process
 * that reads and writes the subtypes over GraphQL but must not run the server's rules imports this alone.
 */
export * from './generated/entity_subclasses.js';
