export const EXPECTED_BUNDLES: Record<string, number> = {
    'collab-world': 4,
    'people-fls': 3,
    'parent-assignees': 6,
    'room': 12,
    'write-gates': 10,
    'extensions': 12,
    'subtypes': 7,
    'row-filters': 4,
    'library': 6,
    'agent': 10,
    'features': 5,
    'stage1': 11,
    'stage2': 5,
    'stage3': 4,
};

export const EXPECTED_CLIENT_BUNDLES: Record<string, number> = {
    'collab-world': 4,
    'people-fls': 3,
    'parent-assignees': 6,
    'room': 11,
    'write-gates': 8,
    'row-filters': 4,
    'library': 8,
    'agent': 7,
    'features': 5,
    'lifecycle': 6,
    'subtypes': 4,
    'stage1': 8,
    'stage2': 4,
    'stage3': 2,
};
