/** @type {import('@memberjunction/config').MJConfig} */
//
// CodeGen for the example space types' own schema. Credentials come from the environment. includeSchemas is the blast radius:
// this run generates only __mj_BizAppsCollabExamples, into this package. The shipped schema (__mj_BizAppsCollaboration) is
// generated by the repo's own config, into the shipped packages; nothing here is for shipping.
//
// Run from this folder:  pnpm exec mj codegen
//
module.exports = {
  dbHost: process.env.DB_HOST || 'localhost',
  dbPort: process.env.DB_PORT ? parseInt(process.env.DB_PORT, 10) : 1433,
  dbDatabase: process.env.DB_DATABASE,
  dbUsername: process.env.DB_USERNAME,
  dbPassword: process.env.DB_PASSWORD,
  dbTrustServerCertificate:
    process.env.DB_TRUST_SERVER_CERTIFICATE === '1' ||
    process.env.DB_TRUST_SERVER_CERTIFICATE === 'true',
  coreSchema: process.env.MJ_CORE_SCHEMA || '__mj',

  entityPackageName: '@mj-biz-apps/collaboration-example-space-types/entities',

  // Declares ExampleBoard and ExampleRoom as IsA children of Spaces
  additionalSchemaInfo: './codegen-schema-info.json',

  output: [
    { type: 'SQL', directory: './SQL Scripts/generated', appendOutputCode: true },
    { type: 'Angular', directory: './src/generated/forms', options: [{ name: 'maxComponentsPerModule', value: 20 }] },
    { type: 'GraphQLServer', directory: './src/generated/server' },
    { type: 'EntitySubclasses', directory: './src/generated/entities' },
  ],

  newEntityDefaults: {
    NameRulesBySchema: [
      { SchemaName: '${mj_core_schema}', EntityNamePrefix: 'MJ: ' },
      { SchemaName: '__mj_BizAppsCollabExamples', EntityNamePrefix: 'MJ_BizApps_Collaboration_Examples: ', EntityNameSuffix: '' },
    ],
  },

  includeSchemas: ['__mj_BizAppsCollabExamples'],
  excludeSchemas: ['sys', 'staging', 'dbo', '__mj'],

  advancedGeneration: { enableAdvancedGeneration: false },

  fileEmit: { perSchema: true },

  SQLOutput: {
    enabled: true,
    folderPath: './migrations/codegen/',
    appendToFile: false,
    convertCoreSchemaToFlywayMigrationFile: true,
    omitRecurringScriptsFromLog: false,
    schemaPlaceholders: [
      { schema: '__mj_BizAppsCollabExamples', placeholder: '${flyway:defaultSchema}' },
      { schema: '__mj_BizAppsCollaboration', placeholder: '__mj_BizAppsCollaboration' },
      { schema: '__mj', placeholder: '${mjSchema}' },
    ],
  },
};
