-- =============================================================================
--  BizApps Collaboration baseline for __mj_BizAppsCollabExamples
--
--  The baseline of the __mj_BizAppsCollabExamples schema: one file in place of the V stack it replaces (item 144).
--  Built by scripts/build-baseline.mjs from COLLAB_S1_STACK, a database that held MemberJunction core, bizapps-common,
--  bizapps-tasks and this app's migrations alone. Section 1 is the schema's DDL as MemberJunction's baseline module
--  introspects it; section 2, under CodeGen's banner, is CodeGen's capture. Filters, permissions and JSONType
--  settings stay JSON under metadata/ and are pushed with mj sync push.
--
--  Every object is created from empty: there is no IF NOT EXISTS, since a baseline applies only to a database
--  that has none of this app's migrations.
-- =============================================================================
-- ============================================================================
-- BizApps Collaboration baseline for __mj_BizAppsCollabExamples
-- Baseline version : v0.1.x
-- Generated at     : 2026-10-01T22:01:00Z
-- Generator        : @memberjunction/cli baseline build
-- ============================================================================
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET NOCOUNT ON;
GO

-- Schemas
IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = N'${flyway:defaultSchema}')
    EXEC('CREATE SCHEMA [${flyway:defaultSchema}]');
GO

-- Tables

CREATE TABLE [${flyway:defaultSchema}].[ExampleBoard] (
    [ID] UNIQUEIDENTIFIER NOT NULL,
    [TermName] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
    [MeetingCadence] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NextMeetingDate] DATETIMEOFFSET(7) NULL,
    [NextMeetingLocation] NVARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [QuorumPercentage] INT NOT NULL,
    [BoardCharterUrl] NVARCHAR(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [__mj_CreatedAt] DATETIMEOFFSET(7) NOT NULL,
    [__mj_UpdatedAt] DATETIMEOFFSET(7) NOT NULL,
    CONSTRAINT [PK_ExampleBoard] PRIMARY KEY CLUSTERED ([ID])
);
GO

-- Default constraints
ALTER TABLE [${flyway:defaultSchema}].[ExampleBoard] ADD CONSTRAINT [DF_ExampleBoard_Quorum] DEFAULT ((50)) FOR [QuorumPercentage];
GO
ALTER TABLE [${flyway:defaultSchema}].[ExampleBoard] ADD CONSTRAINT [DF___mj_BizAppsCollabExamples_ExampleBoard___mj_CreatedAt] DEFAULT (getutcdate()) FOR [__mj_CreatedAt];
GO
ALTER TABLE [${flyway:defaultSchema}].[ExampleBoard] ADD CONSTRAINT [DF___mj_BizAppsCollabExamples_ExampleBoard___mj_UpdatedAt] DEFAULT (getutcdate()) FOR [__mj_UpdatedAt];
GO

-- Views
GO
CREATE VIEW [${flyway:defaultSchema}].[vwExampleBoards]
AS
SELECT
    e.*,
    __mj_isa_p1.[SpaceTypeID],
    __mj_isa_p1.[ParentID],
    __mj_isa_p1.[Name],
    __mj_isa_p1.[Description],
    __mj_isa_p1.[OwnerID],
    __mj_isa_p1.[InheritsMembership],
    __mj_isa_p1.[AgentRetrieval],
    __mj_isa_p1.[StartedAt],
    __mj_isa_p1.[ClosedAt],
    __mj_isa_p1.[AllowParentAssignees],
    __mj_isa_p1.[PlannedCloseAt],
    __mj_isa_p1.[IconClass],
    __mj_isa_p1.[Color],
    __mj_isa_p1.[BackgroundImageURL],
    __mj_isa_p1.[Configuration],
    __mj_isa_p1.[StatusID]
FROM
    [${flyway:defaultSchema}].[ExampleBoard] AS e
INNER JOIN
    [__mj_BizAppsCollaboration].[Space] AS __mj_isa_p1
  ON
    [e].[ID] = __mj_isa_p1.[ID]
GO

-- Procedures
GO
CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateExampleBoard]
    @ID uniqueidentifier = NULL,
    @TermName nvarchar(100),
    @MeetingCadence_Clear bit = 0,
    @MeetingCadence nvarchar(100) = NULL,
    @NextMeetingDate_Clear bit = 0,
    @NextMeetingDate datetimeoffset = NULL,
    @NextMeetingLocation_Clear bit = 0,
    @NextMeetingLocation nvarchar(255) = NULL,
    @QuorumPercentage int = NULL,
    @BoardCharterUrl_Clear bit = 0,
    @BoardCharterUrl nvarchar(500) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @ActualID UNIQUEIDENTIFIER = ISNULL(@ID, NEWID())
    INSERT INTO
    [${flyway:defaultSchema}].[ExampleBoard]
        (
            [TermName],
                [MeetingCadence],
                [NextMeetingDate],
                [NextMeetingLocation],
                [QuorumPercentage],
                [BoardCharterUrl],
                [ID]
        )
    VALUES
        (
            @TermName,
                CASE WHEN @MeetingCadence_Clear = 1 THEN NULL ELSE ISNULL(@MeetingCadence, NULL) END,
                CASE WHEN @NextMeetingDate_Clear = 1 THEN NULL ELSE ISNULL(@NextMeetingDate, NULL) END,
                CASE WHEN @NextMeetingLocation_Clear = 1 THEN NULL ELSE ISNULL(@NextMeetingLocation, NULL) END,
                ISNULL(@QuorumPercentage, 50),
                CASE WHEN @BoardCharterUrl_Clear = 1 THEN NULL ELSE ISNULL(@BoardCharterUrl, NULL) END,
                @ActualID
        )
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwExampleBoards] WHERE [ID] = @ActualID
END
GO
CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteExampleBoard]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ExampleBoard]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateExampleBoard]
    @ID uniqueidentifier,
    @TermName nvarchar(100) = NULL,
    @MeetingCadence_Clear bit = 0,
    @MeetingCadence nvarchar(100) = NULL,
    @NextMeetingDate_Clear bit = 0,
    @NextMeetingDate datetimeoffset = NULL,
    @NextMeetingLocation_Clear bit = 0,
    @NextMeetingLocation nvarchar(255) = NULL,
    @QuorumPercentage int = NULL,
    @BoardCharterUrl_Clear bit = 0,
    @BoardCharterUrl nvarchar(500) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ExampleBoard]
    SET
        [TermName] = ISNULL(@TermName, [TermName]),
        [MeetingCadence] = CASE WHEN @MeetingCadence_Clear = 1 THEN NULL ELSE ISNULL(@MeetingCadence, [MeetingCadence]) END,
        [NextMeetingDate] = CASE WHEN @NextMeetingDate_Clear = 1 THEN NULL ELSE ISNULL(@NextMeetingDate, [NextMeetingDate]) END,
        [NextMeetingLocation] = CASE WHEN @NextMeetingLocation_Clear = 1 THEN NULL ELSE ISNULL(@NextMeetingLocation, [NextMeetingLocation]) END,
        [QuorumPercentage] = ISNULL(@QuorumPercentage, [QuorumPercentage]),
        [BoardCharterUrl] = CASE WHEN @BoardCharterUrl_Clear = 1 THEN NULL ELSE ISNULL(@BoardCharterUrl, [BoardCharterUrl]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwExampleBoards] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwExampleBoards]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

-- Triggers
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateExampleBoard
ON [${flyway:defaultSchema}].[ExampleBoard]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ExampleBoard]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ExampleBoard] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

-- Foreign keys
ALTER TABLE [${flyway:defaultSchema}].[ExampleBoard] ADD CONSTRAINT [FK_ExampleBoard_Space] FOREIGN KEY ([ID]) REFERENCES [__mj_BizAppsCollaboration].[Space] ([ID]);
GO

-- Permissions
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleBoard] TO [cdp_Developer];
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteExampleBoard] TO [cdp_Developer];
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleBoard] TO [cdp_Developer];
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwExampleBoards] TO [cdp_Developer];
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleBoard] TO [cdp_Integration];
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteExampleBoard] TO [cdp_Integration];
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleBoard] TO [cdp_Integration];
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwExampleBoards] TO [cdp_Integration];
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleBoard] TO [cdp_UI];
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleBoard] TO [cdp_UI];
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwExampleBoards] TO [cdp_UI];
GO

-- Extended properties (descriptions etc.)
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'A link to the board charter.', @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleBoard', @level2type = N'COLUMN', @level2name = N'BoardCharterUrl';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'The Space this board specialises: the same value as Space.ID.', @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleBoard', @level2type = N'COLUMN', @level2name = N'ID';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'How often the board meets, in words: "Monthly", "First Tuesday".', @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleBoard', @level2type = N'COLUMN', @level2name = N'MeetingCadence';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'When the next meeting is.', @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleBoard', @level2type = N'COLUMN', @level2name = N'NextMeetingDate';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Where the next meeting is.', @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleBoard', @level2type = N'COLUMN', @level2name = N'NextMeetingLocation';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'The percentage of members who must attend for a vote to count. Defaults to 50.', @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleBoard', @level2type = N'COLUMN', @level2name = N'QuorumPercentage';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'The term the board sits for, for example "2026 to 2027".', @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleBoard', @level2type = N'COLUMN', @level2name = N'TermName';
GO
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'A board: a space of the example-board type, with the terms its members sit under. Shares its primary key with the Space row it specialises.', @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleBoard';
GO


-- =============================================================================
-- GENERATED BY MemberJunction CodeGen — DO NOT EDIT BY HAND
-- =============================================================================
-- CodeGen's capture, as the rows the migration stack left in MemberJunction's metadata tables on COLLAB_S1_STACK
-- (1 entities in __mj_BizAppsCollabExamples), dumped by scripts/build-baseline.mjs. Role permissions here are the
-- defaults CodeGen writes for a new entity; the filters on them, the JSON types and the other roles come from metadata/.

-- [${mjSchema}].[Application]: 1 row(s)
INSERT INTO [${mjSchema}].[Application] ([ID], [Name], [Description], [Icon], [DefaultForNewUser], [SchemaAutoAddNewEntities], [Color], [DefaultNavItems], [ClassName], [DefaultSequence], [Status], [NavigationStyle], [TopNavLocation], [HideNavBarIconWhenActive], [Path], [AutoUpdatePath], [AgentSettings], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'FFF92204-28DC-4FF4-83C6-81DC7D8A46B2', N'${flyway:defaultSchema}', N'Generated for schema', NULL, 0, N'${flyway:defaultSchema}', NULL, NULL, NULL, 100, N'Active', N'App Switcher', NULL, 0, N'mjbizappscollabexamples', 1, NULL, GETUTCDATE(), GETUTCDATE());
-- [${mjSchema}].[ApplicationRole]: 3 row(s)
INSERT INTO [${mjSchema}].[ApplicationRole] ([ID], [ApplicationID], [RoleID], [CanAccess], [CanAdmin], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'8B614E3E-F36B-1410-89A8-007AA2BDA0B9', N'FFF92204-28DC-4FF4-83C6-81DC7D8A46B2', N'DEAFCCEC-6A37-EF11-86D4-000D3A4E707E', 1, 1, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[ApplicationRole] ([ID], [ApplicationID], [RoleID], [CanAccess], [CanAdmin], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'8E614E3E-F36B-1410-89A8-007AA2BDA0B9', N'FFF92204-28DC-4FF4-83C6-81DC7D8A46B2', N'DFAFCCEC-6A37-EF11-86D4-000D3A4E707E', 1, 0, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[ApplicationRole] ([ID], [ApplicationID], [RoleID], [CanAccess], [CanAdmin], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'88614E3E-F36B-1410-89A8-007AA2BDA0B9', N'FFF92204-28DC-4FF4-83C6-81DC7D8A46B2', N'E0AFCCEC-6A37-EF11-86D4-000D3A4E707E', 1, 0, GETUTCDATE(), GETUTCDATE());
-- [${mjSchema}].[Entity]: 1 row(s)
INSERT INTO [${mjSchema}].[Entity] ([ID], [ParentID], [Name], [NameSuffix], [Description], [AutoUpdateDescription], [BaseTable], [BaseView], [BaseViewGenerated], [SchemaName], [VirtualEntity], [TrackRecordChanges], [AuditRecordAccess], [AuditViewRuns], [IncludeInAPI], [AllowAllRowsAPI], [AllowUpdateAPI], [AllowCreateAPI], [AllowDeleteAPI], [CustomResolverAPI], [AllowUserSearchAPI], [FullTextSearchEnabled], [FullTextCatalog], [FullTextCatalogGenerated], [FullTextIndex], [FullTextIndexGenerated], [FullTextSearchFunction], [FullTextSearchFunctionGenerated], [UserViewMaxRows], [spCreate], [spUpdate], [spDelete], [spCreateGenerated], [spUpdateGenerated], [spDeleteGenerated], [CascadeDeletes], [DeleteType], [AllowRecordMerge], [spMatch], [RelationshipDefaultDisplayType], [UserFormGenerated], [EntityObjectSubclassName], [EntityObjectSubclassImport], [PreferredCommunicationField], [Icon], [ScopeDefault], [RowsToPackWithSchema], [RowsToPackSampleMethod], [RowsToPackSampleCount], [RowsToPackSampleOrder], [AutoRowCountFrequency], [RowCount], [RowCountRunAt], [Status], [DisplayName], [AllowMultipleSubtypes], [AutoUpdateFullTextSearch], [AutoUpdateAllowUserSearchAPI], [TrustServerCacheCompletely], [SupportsGeoCoding], [AutoUpdateSupportsGeoCoding], [AllowCaching], [DetectExternalChanges], [ExternalDataSourceID], [ExternalObjectName], [GeneratedBaseViewName], [AllowDirectSQLInsert], [AllowDirectSQLUpdate], [AllowDirectSQLDelete], [Configuration], [SubtypeSelector], [EnableFieldLevelSecurity], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', N'3648DC35-1DC4-4ED6-A1A6-5D87271A54DB', N'MJ_BizApps_Collaboration_Examples: Example Boards', NULL, N'A board: a space of the example-board type, with the terms its members sit under. Shares its primary key with the Space row it specialises.', 1, N'ExampleBoard', N'vwExampleBoards', 1, N'${flyway:defaultSchema}', 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, NULL, 1, NULL, 1, NULL, 1, 1000, NULL, NULL, NULL, 1, 1, 1, 0, N'Hard', 0, NULL, N'Search', 1, NULL, NULL, NULL, NULL, NULL, N'None', N'random', 0, NULL, NULL, NULL, NULL, N'Active', N'Example Boards', 0, 1, 1, 1, 0, 1, 0, 0, NULL, NULL, NULL, 0, 0, 0, NULL, NULL, 0, GETUTCDATE(), GETUTCDATE());
-- [${mjSchema}].[ApplicationEntity]: 1 row(s)
INSERT INTO [${mjSchema}].[ApplicationEntity] ([ID], [ApplicationID], [EntityID], [Sequence], [DefaultForNewUser], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'91614E3E-F36B-1410-89A8-007AA2BDA0B9', N'FFF92204-28DC-4FF4-83C6-81DC7D8A46B2', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 1, 1, GETUTCDATE(), GETUTCDATE());
-- [${mjSchema}].[EntityField]: 25 row(s)
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'479F5E9E-C317-44AF-9A4D-E865DF544E35', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 1, N'ID', N'ID', N'The Space this board specialises: the same value as Space.ID.', 1, 1, 1, NULL, N'uniqueidentifier', 16, 0, 0, 0, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 0, 1, 0, 0, NULL, 1, N'Details', 0, 0, N'3648DC35-1DC4-4ED6-A1A6-5D87271A54DB', N'ID', 1, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'71006302-7658-4A57-B5C6-554E24990B36', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 2, N'TermName', N'Term Name', N'The term the board sits for, for example "2026 to 2027".', 1, 0, 0, NULL, N'nvarchar', 200, 0, 0, 0, NULL, 0, N'None', NULL, NULL, 1, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 0, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'2B755AD7-4321-499E-9E44-52E72093C845', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 3, N'MeetingCadence', N'Meeting Cadence', N'How often the board meets, in words: "Monthly", "First Tuesday".', 1, 0, 0, NULL, N'nvarchar', 200, 0, 0, 1, NULL, 0, N'None', NULL, NULL, 1, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 0, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'65B6BC73-9340-4329-B3F8-451176F194FD', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 4, N'NextMeetingDate', N'Next Meeting Date', N'When the next meeting is.', 1, 0, 0, NULL, N'datetimeoffset', 10, 34, 7, 1, NULL, 0, N'None', NULL, NULL, 1, NULL, 100, 1, 1, 0, 0, NULL, 1, N'Details', 0, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'2AD1E33C-81C2-4BC3-8CE5-C5CD426B5BA8', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 5, N'NextMeetingLocation', N'Next Meeting Location', N'Where the next meeting is.', 1, 0, 0, NULL, N'nvarchar', 510, 0, 0, 1, NULL, 0, N'None', NULL, NULL, 1, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 0, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'3465838C-CEF1-49EE-9751-C9AB0ABBEE4B', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 6, N'QuorumPercentage', N'Quorum Percentage', N'The percentage of members who must attend for a vote to count. Defaults to 50.', 1, 0, 0, NULL, N'int', 4, 10, 0, 0, N'((50))', 0, N'None', NULL, NULL, 0, NULL, 50, 1, 1, 0, 0, NULL, 1, N'Details', 0, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'2CD0A793-062F-40BE-835B-54E8C9AFEA62', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 7, N'BoardCharterUrl', N'Board Charter Url', N'A link to the board charter.', 1, 0, 0, NULL, N'nvarchar', 1000, 0, 0, 1, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 0, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'939216B9-C98C-4F24-95F3-11DDE471322C', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 8, N'__mj_CreatedAt', N'Created At', NULL, 1, 0, 0, NULL, N'datetimeoffset', 10, 34, 7, 0, N'(getutcdate())', 0, N'None', NULL, NULL, 0, NULL, 100, 0, 1, 0, 0, NULL, 1, N'Details', 0, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'CDA4EA97-A851-46E0-B1EF-BF57808B3DE3', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 9, N'__mj_UpdatedAt', N'Updated At', NULL, 1, 0, 0, NULL, N'datetimeoffset', 10, 34, 7, 0, N'(getutcdate())', 0, N'None', NULL, NULL, 0, NULL, 100, 0, 1, 0, 0, NULL, 1, N'Details', 0, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'3F10F9D2-3297-49E3-A4E8-BE3BE1168E16', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 10, N'SpaceTypeID', N'Space Type ID', NULL, 1, 0, 0, NULL, N'uniqueidentifier', 16, 0, 0, 0, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'A99DA16D-5EEC-47DC-AE83-7D0AAD017962', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 11, N'ParentID', N'Parent ID', NULL, 1, 0, 0, NULL, N'uniqueidentifier', 16, 0, 0, 1, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'B59136E3-BAF7-479B-A076-F2F315A59CA2', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 12, N'Name', N'Name', NULL, 1, 0, 0, NULL, N'nvarchar', 400, 0, 0, 0, NULL, 0, N'None', NULL, NULL, 1, NULL, 150, 1, 1, 1, 0, NULL, 1, N'Details', 1, 1, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'B1217E8F-9906-49E1-A57C-1379A106DE04', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 13, N'Description', N'Description', NULL, 1, 0, 0, NULL, N'nvarchar', -1, 0, 0, 1, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'9734DE40-E014-4C38-8C20-F41C9485A4B8', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 14, N'OwnerID', N'Owner ID', NULL, 1, 0, 0, NULL, N'uniqueidentifier', 16, 0, 0, 0, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'0702028A-6928-4606-870F-93C49D4FB1AF', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 15, N'InheritsMembership', N'Inherits Membership', NULL, 1, 0, 0, NULL, N'bit', 1, 1, 0, 0, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'2ABB28E4-2415-47E9-B48F-D7C425DBAE3E', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 16, N'AgentRetrieval', N'Agent Retrieval', NULL, 1, 0, 0, NULL, N'nvarchar', 60, 0, 0, 0, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'B6B6CA71-F62E-4C1E-9E8E-0FBB5EE2CCFD', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 17, N'StartedAt', N'Started At', NULL, 1, 0, 0, NULL, N'datetimeoffset', 10, 34, 7, 1, NULL, 0, N'None', NULL, NULL, 0, NULL, 100, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'2D8BF0B1-D302-46F7-8C2C-9B85C2437164', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 18, N'ClosedAt', N'Closed At', NULL, 1, 0, 0, NULL, N'datetimeoffset', 10, 34, 7, 1, NULL, 0, N'None', NULL, NULL, 0, NULL, 100, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'77DF11AB-DD7C-4416-93EA-A163AFC8FFD4', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 19, N'AllowParentAssignees', N'Allow Parent Assignees', NULL, 1, 0, 0, NULL, N'bit', 1, 1, 0, 0, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'8BD6ABEB-25D4-41AB-95C9-D735C2A669CC', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 20, N'PlannedCloseAt', N'Planned Close At', NULL, 1, 0, 0, NULL, N'datetimeoffset', 10, 34, 7, 1, NULL, 0, N'None', NULL, NULL, 0, NULL, 100, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'342F0C2B-5263-4040-A882-D912FA7575B1', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 21, N'IconClass', N'Icon Class', NULL, 1, 0, 0, NULL, N'nvarchar', 200, 0, 0, 1, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'0FA840BF-1373-43DA-A564-A861964A3634', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 22, N'Color', N'Color', NULL, 1, 0, 0, NULL, N'nvarchar', 100, 0, 0, 1, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'5EE974BA-F0AA-4665-B056-82F447FD15A2', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 23, N'BackgroundImageURL', N'Background Image URL', NULL, 1, 0, 0, NULL, N'nvarchar', 2000, 0, 0, 1, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'33419EA2-64C2-465D-9AB8-59F7F791BAB2', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 24, N'Configuration', N'Configuration', NULL, 1, 0, 0, NULL, N'nvarchar', -1, 0, 0, 1, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 0, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityField] ([ID], [EntityID], [Sequence], [Name], [DisplayName], [Description], [AutoUpdateDescription], [IsPrimaryKey], [IsUnique], [Category], [Type], [Length], [Precision], [Scale], [AllowsNull], [DefaultValue], [AutoIncrement], [ValueListType], [ExtendedType], [CodeType], [DefaultInView], [ViewCellTemplate], [DefaultColumnWidth], [AllowUpdateAPI], [AllowUpdateInView], [IncludeInUserSearchAPI], [FullTextSearchEnabled], [UserSearchParamFormatAPI], [IncludeInGeneratedForm], [GeneratedFormSection], [IsVirtual], [IsNameField], [RelatedEntityID], [RelatedEntityFieldName], [IncludeRelatedEntityNameFieldInBaseView], [RelatedEntityNameFieldMap], [RelatedEntityDisplayType], [EntityIDFieldName], [ScopeDefault], [AutoUpdateRelatedEntityInfo], [ValuesToPackWithSchema], [Status], [AutoUpdateIsNameField], [AutoUpdateDefaultInView], [AutoUpdateCategory], [AutoUpdateDisplayName], [AutoUpdateIncludeInUserSearchAPI], [Encrypt], [EncryptionKeyID], [AllowDecryptInAPI], [SendEncryptedValue], [IsSoftPrimaryKey], [IsSoftForeignKey], [RelatedEntityJoinFields], [JSONType], [JSONTypeIsArray], [JSONTypeDefinition], [UserSearchPredicateAPI], [AutoUpdateUserSearchPredicate], [AutoUpdateFullTextSearch], [AutoUpdateExtendedType], [IsComputed], [EmbeddedRecord], [Configuration], [RelatedEntityFilter], [RelatedEntityOrderBy], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'9B3B0381-95C2-4868-BE65-14EB2BEB7701', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 25, N'StatusID', N'Status', NULL, 1, 0, 0, NULL, N'uniqueidentifier', 16, 0, 0, 1, NULL, 0, N'None', NULL, NULL, 0, NULL, 150, 1, 1, 0, 0, NULL, 1, N'Details', 1, 0, NULL, NULL, 1, NULL, N'Search', NULL, NULL, 1, N'Auto', N'Active', 1, 1, 1, 1, 1, 0, NULL, 0, 0, 0, 0, NULL, NULL, 0, NULL, N'Contains', 1, 1, 1, 0, NULL, NULL, NULL, NULL, GETUTCDATE(), GETUTCDATE());
-- [${mjSchema}].[EntityRelationship]: 1 row(s)
INSERT INTO [${mjSchema}].[EntityRelationship] ([ID], [EntityID], [Sequence], [RelatedEntityID], [BundleInAPI], [IncludeInParentAllQuery], [Type], [EntityKeyField], [RelatedEntityJoinField], [JoinView], [JoinEntityJoinField], [JoinEntityInverseJoinField], [DisplayInForm], [DisplayLocation], [DisplayName], [DisplayIconType], [DisplayIcon], [DisplayUserViewID], [DisplayComponentID], [DisplayComponentConfiguration], [AutoUpdateFromSchema], [AdditionalFieldsToInclude], [AutoUpdateAdditionalFieldsToInclude], [RelatedRecordCollection], [Configuration], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'629E09F8-067C-4300-BCD8-B474179371B8', N'3648DC35-1DC4-4ED6-A1A6-5D87271A54DB', 11, N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 1, 0, N'One To Many         ', NULL, N'ID', NULL, NULL, NULL, 1, N'After Field Tabs', NULL, N'Related Entity Icon', NULL, NULL, NULL, NULL, 1, NULL, 1, NULL, NULL, GETUTCDATE(), GETUTCDATE());
-- [${mjSchema}].[EntityPermission]: 3 row(s)
INSERT INTO [${mjSchema}].[EntityPermission] ([ID], [EntityID], [RoleID], [CanCreate], [CanRead], [CanUpdate], [CanDelete], [ReadRLSFilterID], [CreateRLSFilterID], [UpdateRLSFilterID], [DeleteRLSFilterID], [Type], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'97614E3E-F36B-1410-89A8-007AA2BDA0B9', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', N'DEAFCCEC-6A37-EF11-86D4-000D3A4E707E', 1, 1, 1, 1, NULL, NULL, NULL, NULL, N'Allow', GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityPermission] ([ID], [EntityID], [RoleID], [CanCreate], [CanRead], [CanUpdate], [CanDelete], [ReadRLSFilterID], [CreateRLSFilterID], [UpdateRLSFilterID], [DeleteRLSFilterID], [Type], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'9A614E3E-F36B-1410-89A8-007AA2BDA0B9', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', N'DFAFCCEC-6A37-EF11-86D4-000D3A4E707E', 1, 1, 1, 1, NULL, NULL, NULL, NULL, N'Allow', GETUTCDATE(), GETUTCDATE());
INSERT INTO [${mjSchema}].[EntityPermission] ([ID], [EntityID], [RoleID], [CanCreate], [CanRead], [CanUpdate], [CanDelete], [ReadRLSFilterID], [CreateRLSFilterID], [UpdateRLSFilterID], [DeleteRLSFilterID], [Type], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES (N'94614E3E-F36B-1410-89A8-007AA2BDA0B9', N'CE573816-2129-4DCD-AAF4-FE837F1A0C57', N'E0AFCCEC-6A37-EF11-86D4-000D3A4E707E', 0, 1, 0, 0, NULL, NULL, NULL, NULL, N'Allow', GETUTCDATE(), GETUTCDATE());
GO
-- End of baseline.
GO
