-- =============================================================================
-- Stage 1 for the example board: the parent's new column, and the five it lost
-- =============================================================================
-- The board is an IS-A child of Space. Stage 1 (the app's V202610012100) gives Space a StatusID and takes away
-- AnchorEntityID, AnchorRecordID, PostCloseAccess, PostCloseAccessDays and Retention; the board's view and entity
-- fields follow the parent. Nothing hand-written here: the board's first migration (V202609290300) had its view and
-- the parent-field rows for those five columns edited out by hand, so that a database built from empty takes it after
-- the app's stage 1 migration, and this file holds what CodeGen then generated for the board on such a database.
--
-- Placeholders: ${flyway:defaultSchema} this schema (__mj_BizAppsCollabExamples); ${mjSchema} MJ core.
-- =============================================================================


















































-- =============================================================================
-- GENERATED BY MemberJunction CodeGen — DO NOT EDIT BY HAND
-- =============================================================================
/* SQL text to update existing entities from schema */
EXEC [${mjSchema}].[spUpdateExistingEntitiesFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to update existing entity fields from schema */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* Create IS-A parent field StatusID on MJ_BizApps_Collaboration_Examples: Example Boards */
INSERT INTO [${mjSchema}].[EntityField] (
                  [ID], [EntityID], [Name], [Type], [AllowsNull],
                  [Length], [Precision], [Scale],
                  [Sequence], [IsVirtual], [AllowUpdateAPI],
                  [IsPrimaryKey], [IsUnique],
                  [__mj_CreatedAt], [__mj_UpdatedAt])
               VALUES (
                  '9b3b0381-95c2-4868-be65-14eb2beb7701', 'CE573816-2129-4DCD-AAF4-FE837F1A0C57', 'StatusID',
                  'uniqueidentifier', 1,
                  16, 0, 0,
                  (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = 'CE573816-2129-4DCD-AAF4-FE837F1A0C57'), 1, 1, 0, 0,
                  GETUTCDATE(), GETUTCDATE());

/* Update entity timestamp for MJ_BizApps_Collaboration_Examples: Example Boards after IS-A field sync */
UPDATE [${mjSchema}].[Entity] SET [__mj_UpdatedAt]=GETUTCDATE() WHERE ID='CE573816-2129-4DCD-AAF4-FE837F1A0C57';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to update display name for field StatusID */
UPDATE [${mjSchema}].[EntityField] SET [__mj_UpdatedAt]=GETUTCDATE(), DisplayName = 'Status' WHERE ID = '9B3B0381-95C2-4868-BE65-14EB2BEB7701';

/* SQL text to sync schema info from database schemas */
EXEC [${mjSchema}].[spUpdateSchemaInfoFromDatabase] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* Base View SQL for MJ_BizApps_Collaboration_Examples: Example Boards */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Boards
-- Item: vwExampleBoards
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Collaboration_Examples: Example Boards
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ExampleBoard
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwExampleBoards]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwExampleBoards];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwExampleBoards]
AS
SELECT
    e.*,
    ${mjSchema}_isa_p1.[SpaceTypeID],
    ${mjSchema}_isa_p1.[ParentID],
    ${mjSchema}_isa_p1.[Name],
    ${mjSchema}_isa_p1.[Description],
    ${mjSchema}_isa_p1.[OwnerID],
    ${mjSchema}_isa_p1.[InheritsMembership],
    ${mjSchema}_isa_p1.[AgentRetrieval],
    ${mjSchema}_isa_p1.[StartedAt],
    ${mjSchema}_isa_p1.[ClosedAt],
    ${mjSchema}_isa_p1.[AllowParentAssignees],
    ${mjSchema}_isa_p1.[PlannedCloseAt],
    ${mjSchema}_isa_p1.[IconClass],
    ${mjSchema}_isa_p1.[Color],
    ${mjSchema}_isa_p1.[BackgroundImageURL],
    ${mjSchema}_isa_p1.[Configuration],
    ${mjSchema}_isa_p1.[StatusID]
FROM
    [${flyway:defaultSchema}].[ExampleBoard] AS e
INNER JOIN
    [${mjSchema}_BizAppsCollaboration].[Space] AS ${mjSchema}_isa_p1
  ON
    [e].[ID] = ${mjSchema}_isa_p1.[ID]
GO
REVOKE SELECT ON [${flyway:defaultSchema}].[vwExampleBoards] FROM [cdp_Developer]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwExampleBoards] FROM [cdp_Integration]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwExampleBoards] FROM [cdp_UI]
GRANT SELECT ON [${flyway:defaultSchema}].[vwExampleBoards] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Collaboration_Examples: Example Boards */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Boards
-- Item: Permissions for vwExampleBoards
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

REVOKE SELECT ON [${flyway:defaultSchema}].[vwExampleBoards] FROM [cdp_Developer]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwExampleBoards] FROM [cdp_Integration]
REVOKE SELECT ON [${flyway:defaultSchema}].[vwExampleBoards] FROM [cdp_UI]
GRANT SELECT ON [${flyway:defaultSchema}].[vwExampleBoards] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Collaboration_Examples: Example Boards */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Boards
-- Item: spCreateExampleBoard
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ExampleBoard
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateExampleBoard]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateExampleBoard];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateExampleBoard]
    @ID uniqueidentifier = NULL,
    @TermName nvarchar(100),
    @MeetingCadence_Clear bit = 0,
    @MeetingCadence nvarchar(100) = NULL,
    @NextMeetingDate_Clear bit = 0,
    @NextMeetingDate datetimeoffset = NULL,
    @NextMeetingLocation_Clear bit = 0,
    @NextMeetingLocation nvarchar(255) = NULL,
    @QuorumPercentage int = NULL,
    @BoardCharterUrl_Clear bit = 0,
    @BoardCharterUrl nvarchar(500) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @ActualID UNIQUEIDENTIFIER = ISNULL(@ID, NEWID())
    INSERT INTO
    [${flyway:defaultSchema}].[ExampleBoard]
        (
            [TermName],
                [MeetingCadence],
                [NextMeetingDate],
                [NextMeetingLocation],
                [QuorumPercentage],
                [BoardCharterUrl],
                [ID]
        )
    VALUES
        (
            @TermName,
                CASE WHEN @MeetingCadence_Clear = 1 THEN NULL ELSE ISNULL(@MeetingCadence, NULL) END,
                CASE WHEN @NextMeetingDate_Clear = 1 THEN NULL ELSE ISNULL(@NextMeetingDate, NULL) END,
                CASE WHEN @NextMeetingLocation_Clear = 1 THEN NULL ELSE ISNULL(@NextMeetingLocation, NULL) END,
                ISNULL(@QuorumPercentage, 50),
                CASE WHEN @BoardCharterUrl_Clear = 1 THEN NULL ELSE ISNULL(@BoardCharterUrl, NULL) END,
                @ActualID
        )
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwExampleBoards] WHERE [ID] = @ActualID
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleBoard] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleBoard] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleBoard] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Collaboration_Examples: Example Boards */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleBoard] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleBoard] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleBoard] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Collaboration_Examples: Example Boards */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Boards
-- Item: spUpdateExampleBoard
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ExampleBoard
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateExampleBoard]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateExampleBoard];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateExampleBoard]
    @ID uniqueidentifier,
    @TermName nvarchar(100) = NULL,
    @MeetingCadence_Clear bit = 0,
    @MeetingCadence nvarchar(100) = NULL,
    @NextMeetingDate_Clear bit = 0,
    @NextMeetingDate datetimeoffset = NULL,
    @NextMeetingLocation_Clear bit = 0,
    @NextMeetingLocation nvarchar(255) = NULL,
    @QuorumPercentage int = NULL,
    @BoardCharterUrl_Clear bit = 0,
    @BoardCharterUrl nvarchar(500) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ExampleBoard]
    SET
        [TermName] = ISNULL(@TermName, [TermName]),
        [MeetingCadence] = CASE WHEN @MeetingCadence_Clear = 1 THEN NULL ELSE ISNULL(@MeetingCadence, [MeetingCadence]) END,
        [NextMeetingDate] = CASE WHEN @NextMeetingDate_Clear = 1 THEN NULL ELSE ISNULL(@NextMeetingDate, [NextMeetingDate]) END,
        [NextMeetingLocation] = CASE WHEN @NextMeetingLocation_Clear = 1 THEN NULL ELSE ISNULL(@NextMeetingLocation, [NextMeetingLocation]) END,
        [QuorumPercentage] = ISNULL(@QuorumPercentage, [QuorumPercentage]),
        [BoardCharterUrl] = CASE WHEN @BoardCharterUrl_Clear = 1 THEN NULL ELSE ISNULL(@BoardCharterUrl, [BoardCharterUrl]) END
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwExampleBoards] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwExampleBoards]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleBoard] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleBoard] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleBoard] TO [cdp_UI], [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ExampleBoard table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateExampleBoard]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateExampleBoard];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateExampleBoard
ON [${flyway:defaultSchema}].[ExampleBoard]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ExampleBoard]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ExampleBoard] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Collaboration_Examples: Example Boards */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleBoard] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleBoard] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleBoard] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Collaboration_Examples: Example Boards */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Boards
-- Item: spDeleteExampleBoard
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ExampleBoard
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteExampleBoard]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteExampleBoard];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteExampleBoard]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ExampleBoard]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteExampleBoard] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteExampleBoard] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteExampleBoard] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Collaboration_Examples: Example Boards */

REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteExampleBoard] FROM [cdp_Developer]
REVOKE EXECUTE ON [${flyway:defaultSchema}].[spDeleteExampleBoard] FROM [cdp_Integration]
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteExampleBoard] TO [cdp_Developer], [cdp_Integration];
