-- =============================================================================
-- Migration: V202609270001__v0.1.x__Example_Space_Types_Tables.sql
-- Schema: ${flyway:defaultSchema}
-- Test-only tables for ExampleSpaceTypes (example-board and example-room).
-- =============================================================================

IF OBJECT_ID(N'${flyway:defaultSchema}.ExampleBoard', N'U') IS NULL
BEGIN
    CREATE TABLE [${flyway:defaultSchema}].[ExampleBoard] (
        [ID] UNIQUEIDENTIFIER NOT NULL,
        [TermName] NVARCHAR(100) NOT NULL,
        [MeetingCadence] NVARCHAR(100) NULL,
        [NextMeetingDate] DATETIMEOFFSET NULL,
        [NextMeetingLocation] NVARCHAR(255) NULL,
        [QuorumPercentage] INT NOT NULL CONSTRAINT [DF_ExampleBoard_Quorum] DEFAULT (50),
        [BoardCharterUrl] NVARCHAR(500) NULL,
        [__mj_CreatedAt] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_ExampleBoard___mj_CreatedAt] DEFAULT (SYSDATETIMEOFFSET()),
        [__mj_UpdatedAt] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_ExampleBoard___mj_UpdatedAt] DEFAULT (SYSDATETIMEOFFSET()),
        CONSTRAINT [PK_ExampleBoard] PRIMARY KEY CLUSTERED ([ID] ASC),
        CONSTRAINT [FK_ExampleBoard_Space] FOREIGN KEY ([ID]) REFERENCES [${flyway:defaultSchema}].[Space] ([ID]) ON DELETE CASCADE
    );
END;
GO

IF OBJECT_ID(N'${flyway:defaultSchema}.ExampleRoom', N'U') IS NULL
BEGIN
    CREATE TABLE [${flyway:defaultSchema}].[ExampleRoom] (
        [ID] UNIQUEIDENTIFIER NOT NULL,
        [DealID] NVARCHAR(100) NOT NULL,
        [AccountName] NVARCHAR(255) NOT NULL,
        [DealStage] NVARCHAR(50) NOT NULL,
        [CloseDate] DATETIMEOFFSET NULL,
        [DealValue] DECIMAL(18, 2) NULL,
        [WinProbability] INT NULL,
        [__mj_CreatedAt] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_ExampleRoom___mj_CreatedAt] DEFAULT (SYSDATETIMEOFFSET()),
        [__mj_UpdatedAt] DATETIMEOFFSET NOT NULL CONSTRAINT [DF_ExampleRoom___mj_UpdatedAt] DEFAULT (SYSDATETIMEOFFSET()),
        CONSTRAINT [PK_ExampleRoom] PRIMARY KEY CLUSTERED ([ID] ASC),
        CONSTRAINT [FK_ExampleRoom_Space] FOREIGN KEY ([ID]) REFERENCES [${flyway:defaultSchema}].[Space] ([ID]) ON DELETE CASCADE
    );
END;
GO


















































-- =============================================================================
-- GENERATED BY MemberJunction CodeGen — DO NOT EDIT BY HAND
-- =============================================================================
-- Test entity support views and procedures for ExampleBoard and ExampleRoom
