-- =============================================================================
--  example-chapter (the plan's B24, stage 2): a chapter and its members, in the examples' own schema.
--
--  Two tables for a type whose spaces are anchored to a record that has its own life in the data (D26): ExampleChapter is the
--  record a chapter space points at, ExampleChapterMember the rows a chapter's participants reach through the type's data reach
--  (D28) on ChapterID. DuesBalance exists so a field outside the allow-list can be shown to stay hidden. Test-only, like the board.
--  Section 2, under CodeGen's banner, is CodeGen's output for the two tables.
-- =============================================================================

CREATE TABLE [${flyway:defaultSchema}].[ExampleChapter] (
    [ID] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_ExampleChapter_ID] DEFAULT (newsequentialid()),
    [Name] NVARCHAR(200) NOT NULL,
    [Region] NVARCHAR(100) NULL,
    [CharterDate] DATE NULL,
    [Status] NVARCHAR(20) NOT NULL CONSTRAINT [DF_ExampleChapter_Status] DEFAULT (N'Active'),
    [__mj_CreatedAt] DATETIMEOFFSET(7) NOT NULL CONSTRAINT [DF___mj_BizAppsCollabExamples_ExampleChapter___mj_CreatedAt] DEFAULT (getutcdate()),
    [__mj_UpdatedAt] DATETIMEOFFSET(7) NOT NULL CONSTRAINT [DF___mj_BizAppsCollabExamples_ExampleChapter___mj_UpdatedAt] DEFAULT (getutcdate()),
    CONSTRAINT [PK_ExampleChapter] PRIMARY KEY CLUSTERED ([ID]),
    CONSTRAINT [CK_ExampleChapter_Status] CHECK ([Status] IN (N'Active', N'Dormant', N'Closed'))
);
GO

CREATE TABLE [${flyway:defaultSchema}].[ExampleChapterMember] (
    [ID] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_ExampleChapterMember_ID] DEFAULT (newsequentialid()),
    [ChapterID] UNIQUEIDENTIFIER NOT NULL,
    [FirstName] NVARCHAR(100) NOT NULL,
    [LastName] NVARCHAR(100) NOT NULL,
    [Email] NVARCHAR(255) NULL,
    [JoinedAt] DATE NULL,
    [RenewalDate] DATE NULL,
    [DuesBalance] DECIMAL(10, 2) NOT NULL CONSTRAINT [DF_ExampleChapterMember_DuesBalance] DEFAULT ((0)),
    [Status] NVARCHAR(20) NOT NULL CONSTRAINT [DF_ExampleChapterMember_Status] DEFAULT (N'Active'),
    [__mj_CreatedAt] DATETIMEOFFSET(7) NOT NULL CONSTRAINT [DF___mj_BizAppsCollabExamples_ExampleChapterMember___mj_CreatedAt] DEFAULT (getutcdate()),
    [__mj_UpdatedAt] DATETIMEOFFSET(7) NOT NULL CONSTRAINT [DF___mj_BizAppsCollabExamples_ExampleChapterMember___mj_UpdatedAt] DEFAULT (getutcdate()),
    CONSTRAINT [PK_ExampleChapterMember] PRIMARY KEY CLUSTERED ([ID]),
    CONSTRAINT [FK_ExampleChapterMember_Chapter] FOREIGN KEY ([ChapterID]) REFERENCES [${flyway:defaultSchema}].[ExampleChapter] ([ID]),
    CONSTRAINT [CK_ExampleChapterMember_Status] CHECK ([Status] IN (N'Active', N'Lapsed', N'Former'))
);
GO

CREATE INDEX [IX_ExampleChapterMember_ChapterID] ON [${flyway:defaultSchema}].[ExampleChapterMember] ([ChapterID]);
GO

EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'A chapter of the example association: the record a chapter space is anchored to (D26). Test-only, for the example-chapter type.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleChapter';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'The region the chapter serves.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleChapter', @level2type = N'COLUMN', @level2name = N'Region';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Active, Dormant or Closed.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleChapter', @level2type = N'COLUMN', @level2name = N'Status';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'A member of a chapter: the rows a chapter space''s participants reach through the type''s data reach on ChapterID (D28). Test-only.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleChapterMember';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'The member''s dues balance. Outside the type''s allow-list, so a participant never reads it.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleChapterMember', @level2type = N'COLUMN', @level2name = N'DuesBalance';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Active, Lapsed or Former.',
    @level0type = N'SCHEMA', @level0name = N'${flyway:defaultSchema}', @level1type = N'TABLE', @level1name = N'ExampleChapterMember', @level2type = N'COLUMN', @level2name = N'Status';
GO


-- =============================================================================
-- GENERATED BY MemberJunction CodeGen — DO NOT EDIT BY HAND
-- =============================================================================
-- CodeGen's output for the two tables above, run from this folder's mj.config.cjs against a database that held the
-- migrations through the examples' baseline: the entity rows, their fields, values, relationship and permissions, and
-- the views and procedures. Role permissions here are CodeGen's defaults; the data-reach filter and the participant's
-- read on members come from metadata-tests/ (generated by scripts/generate-data-reach-filters.mjs).
-- =============================================================================
/* SQL generated to create new entity MJ_BizApps_Collaboration_Examples: Example Chapters */

      INSERT INTO [${mjSchema}].[Entity] (
         [ID],
         [Name],
         [DisplayName],
         [Description],
         [NameSuffix],
         [BaseTable],
         [BaseView],
         [SchemaName],
         [IncludeInAPI],
         [AllowUserSearchAPI],
         [AllowCaching]
         , [TrackRecordChanges]
         , [AuditRecordAccess]
         , [AuditViewRuns]
         , [AllowAllRowsAPI]
         , [AllowCreateAPI]
         , [AllowUpdateAPI]
         , [AllowDeleteAPI]
         , [UserViewMaxRows]
         , [__mj_CreatedAt]
         , [__mj_UpdatedAt]
      )
      VALUES (
         'eb8761de-34ac-4ff2-ad83-9fe4fb171bb0',
         'MJ_BizApps_Collaboration_Examples: Example Chapters',
         'Example Chapters',
         'A chapter of the example association: the record a chapter space is anchored to (D26). Test-only, for the example-chapter type.',
         NULL,
         'ExampleChapter',
         'vwExampleChapters',
         '${flyway:defaultSchema}',
         1,
         1,
         0
         , 1
         , 0
         , 0
         , 0
         , 1
         , 1
         , 1
         , 1000
         , GETUTCDATE()
         , GETUTCDATE()
      );

/* SQL generated to add new entity MJ_BizApps_Collaboration_Examples: Example Chapters to application ID: 'FFF92204-28DC-4FF4-83C6-81DC7D8A46B2' */
INSERT INTO [${mjSchema}].[ApplicationEntity]
                                       ([ApplicationID], [EntityID], [Sequence], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES
                                       ('FFF92204-28DC-4FF4-83C6-81DC7D8A46B2', 'eb8761de-34ac-4ff2-ad83-9fe4fb171bb0', (SELECT COALESCE(MAX([Sequence]),0)+1 FROM [${mjSchema}].[ApplicationEntity] WHERE [ApplicationID] = 'FFF92204-28DC-4FF4-83C6-81DC7D8A46B2'), GETUTCDATE(), GETUTCDATE());

/* SQL generated to add new permission for entity MJ_BizApps_Collaboration_Examples: Example Chapters for role UI */
INSERT INTO [${mjSchema}].[EntityPermission]
                ([EntityID], [RoleID], [Type], [CanRead], [CanCreate], [CanUpdate], [CanDelete], [__mj_CreatedAt], [__mj_UpdatedAt])
              SELECT CAST('eb8761de-34ac-4ff2-ad83-9fe4fb171bb0' AS uniqueidentifier), CAST('E0AFCCEC-6A37-EF11-86D4-000D3A4E707E' AS uniqueidentifier), 'Allow', 1, 0, 0, 0, GETUTCDATE(), GETUTCDATE()
              WHERE NOT EXISTS (
                SELECT 1 FROM [${mjSchema}].[EntityPermission]
                WHERE [EntityID] = CAST('eb8761de-34ac-4ff2-ad83-9fe4fb171bb0' AS uniqueidentifier) AND [RoleID] = CAST('E0AFCCEC-6A37-EF11-86D4-000D3A4E707E' AS uniqueidentifier) AND [Type] = 'Allow'
              );

/* SQL generated to add new permission for entity MJ_BizApps_Collaboration_Examples: Example Chapters for role Developer */
INSERT INTO [${mjSchema}].[EntityPermission]
                ([EntityID], [RoleID], [Type], [CanRead], [CanCreate], [CanUpdate], [CanDelete], [__mj_CreatedAt], [__mj_UpdatedAt])
              SELECT CAST('eb8761de-34ac-4ff2-ad83-9fe4fb171bb0' AS uniqueidentifier), CAST('DEAFCCEC-6A37-EF11-86D4-000D3A4E707E' AS uniqueidentifier), 'Allow', 1, 1, 1, 1, GETUTCDATE(), GETUTCDATE()
              WHERE NOT EXISTS (
                SELECT 1 FROM [${mjSchema}].[EntityPermission]
                WHERE [EntityID] = CAST('eb8761de-34ac-4ff2-ad83-9fe4fb171bb0' AS uniqueidentifier) AND [RoleID] = CAST('DEAFCCEC-6A37-EF11-86D4-000D3A4E707E' AS uniqueidentifier) AND [Type] = 'Allow'
              );

/* SQL generated to add new permission for entity MJ_BizApps_Collaboration_Examples: Example Chapters for role Integration */
INSERT INTO [${mjSchema}].[EntityPermission]
                ([EntityID], [RoleID], [Type], [CanRead], [CanCreate], [CanUpdate], [CanDelete], [__mj_CreatedAt], [__mj_UpdatedAt])
              SELECT CAST('eb8761de-34ac-4ff2-ad83-9fe4fb171bb0' AS uniqueidentifier), CAST('DFAFCCEC-6A37-EF11-86D4-000D3A4E707E' AS uniqueidentifier), 'Allow', 1, 1, 1, 1, GETUTCDATE(), GETUTCDATE()
              WHERE NOT EXISTS (
                SELECT 1 FROM [${mjSchema}].[EntityPermission]
                WHERE [EntityID] = CAST('eb8761de-34ac-4ff2-ad83-9fe4fb171bb0' AS uniqueidentifier) AND [RoleID] = CAST('DFAFCCEC-6A37-EF11-86D4-000D3A4E707E' AS uniqueidentifier) AND [Type] = 'Allow'
              );

/* SQL generated to create new entity MJ_BizApps_Collaboration_Examples: Example Chapter Members */

      INSERT INTO [${mjSchema}].[Entity] (
         [ID],
         [Name],
         [DisplayName],
         [Description],
         [NameSuffix],
         [BaseTable],
         [BaseView],
         [SchemaName],
         [IncludeInAPI],
         [AllowUserSearchAPI],
         [AllowCaching]
         , [TrackRecordChanges]
         , [AuditRecordAccess]
         , [AuditViewRuns]
         , [AllowAllRowsAPI]
         , [AllowCreateAPI]
         , [AllowUpdateAPI]
         , [AllowDeleteAPI]
         , [UserViewMaxRows]
         , [__mj_CreatedAt]
         , [__mj_UpdatedAt]
      )
      VALUES (
         '963bd9cd-4a10-434c-81d6-4207d2681082',
         'MJ_BizApps_Collaboration_Examples: Example Chapter Members',
         'Example Chapter Members',
         'A member of a chapter: the rows a chapter space''s participants reach through the type''s data reach on ChapterID (D28). Test-only.',
         NULL,
         'ExampleChapterMember',
         'vwExampleChapterMembers',
         '${flyway:defaultSchema}',
         1,
         1,
         0
         , 1
         , 0
         , 0
         , 0
         , 1
         , 1
         , 1
         , 1000
         , GETUTCDATE()
         , GETUTCDATE()
      );

/* SQL generated to add new entity MJ_BizApps_Collaboration_Examples: Example Chapter Members to application ID: 'FFF92204-28DC-4FF4-83C6-81DC7D8A46B2' */
INSERT INTO [${mjSchema}].[ApplicationEntity]
                                       ([ApplicationID], [EntityID], [Sequence], [__mj_CreatedAt], [__mj_UpdatedAt]) VALUES
                                       ('FFF92204-28DC-4FF4-83C6-81DC7D8A46B2', '963bd9cd-4a10-434c-81d6-4207d2681082', (SELECT COALESCE(MAX([Sequence]),0)+1 FROM [${mjSchema}].[ApplicationEntity] WHERE [ApplicationID] = 'FFF92204-28DC-4FF4-83C6-81DC7D8A46B2'), GETUTCDATE(), GETUTCDATE());

/* SQL generated to add new permission for entity MJ_BizApps_Collaboration_Examples: Example Chapter Members for role UI */
INSERT INTO [${mjSchema}].[EntityPermission]
                ([EntityID], [RoleID], [Type], [CanRead], [CanCreate], [CanUpdate], [CanDelete], [__mj_CreatedAt], [__mj_UpdatedAt])
              SELECT CAST('963bd9cd-4a10-434c-81d6-4207d2681082' AS uniqueidentifier), CAST('E0AFCCEC-6A37-EF11-86D4-000D3A4E707E' AS uniqueidentifier), 'Allow', 1, 0, 0, 0, GETUTCDATE(), GETUTCDATE()
              WHERE NOT EXISTS (
                SELECT 1 FROM [${mjSchema}].[EntityPermission]
                WHERE [EntityID] = CAST('963bd9cd-4a10-434c-81d6-4207d2681082' AS uniqueidentifier) AND [RoleID] = CAST('E0AFCCEC-6A37-EF11-86D4-000D3A4E707E' AS uniqueidentifier) AND [Type] = 'Allow'
              );

/* SQL generated to add new permission for entity MJ_BizApps_Collaboration_Examples: Example Chapter Members for role Developer */
INSERT INTO [${mjSchema}].[EntityPermission]
                ([EntityID], [RoleID], [Type], [CanRead], [CanCreate], [CanUpdate], [CanDelete], [__mj_CreatedAt], [__mj_UpdatedAt])
              SELECT CAST('963bd9cd-4a10-434c-81d6-4207d2681082' AS uniqueidentifier), CAST('DEAFCCEC-6A37-EF11-86D4-000D3A4E707E' AS uniqueidentifier), 'Allow', 1, 1, 1, 1, GETUTCDATE(), GETUTCDATE()
              WHERE NOT EXISTS (
                SELECT 1 FROM [${mjSchema}].[EntityPermission]
                WHERE [EntityID] = CAST('963bd9cd-4a10-434c-81d6-4207d2681082' AS uniqueidentifier) AND [RoleID] = CAST('DEAFCCEC-6A37-EF11-86D4-000D3A4E707E' AS uniqueidentifier) AND [Type] = 'Allow'
              );

/* SQL generated to add new permission for entity MJ_BizApps_Collaboration_Examples: Example Chapter Members for role Integration */
INSERT INTO [${mjSchema}].[EntityPermission]
                ([EntityID], [RoleID], [Type], [CanRead], [CanCreate], [CanUpdate], [CanDelete], [__mj_CreatedAt], [__mj_UpdatedAt])
              SELECT CAST('963bd9cd-4a10-434c-81d6-4207d2681082' AS uniqueidentifier), CAST('DFAFCCEC-6A37-EF11-86D4-000D3A4E707E' AS uniqueidentifier), 'Allow', 1, 1, 1, 1, GETUTCDATE(), GETUTCDATE()
              WHERE NOT EXISTS (
                SELECT 1 FROM [${mjSchema}].[EntityPermission]
                WHERE [EntityID] = CAST('963bd9cd-4a10-434c-81d6-4207d2681082' AS uniqueidentifier) AND [RoleID] = CAST('DFAFCCEC-6A37-EF11-86D4-000D3A4E707E' AS uniqueidentifier) AND [Type] = 'Allow'
              );

/* SQL text to update existing entities from schema */
EXEC [${mjSchema}].[spUpdateExistingEntitiesFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to insert 18 new entity field(s) */

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '805a2780-0019-45e7-ab37-c965204e446f' OR (EntityID = '963BD9CD-4A10-434C-81D6-4207D2681082' AND Name = 'ID')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '805a2780-0019-45e7-ab37-c965204e446f',
            '963BD9CD-4A10-434C-81D6-4207D2681082', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '963BD9CD-4A10-434C-81D6-4207D2681082'),
            'ID',
            'ID',
            NULL,
            'uniqueidentifier',
            16,
            0,
            0,
            0,
            'newsequentialid()',
            0,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            1,
            1,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'b8dc89a8-3cc4-41ab-90b4-114721a59ccb' OR (EntityID = '963BD9CD-4A10-434C-81D6-4207D2681082' AND Name = 'ChapterID')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'b8dc89a8-3cc4-41ab-90b4-114721a59ccb',
            '963BD9CD-4A10-434C-81D6-4207D2681082', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '963BD9CD-4A10-434C-81D6-4207D2681082'),
            'ChapterID',
            'Chapter ID',
            NULL,
            'uniqueidentifier',
            16,
            0,
            0,
            0,
            NULL,
            0,
            1,
            0,
            0,
            'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0',
            'ID',
            0,
            0,
            1,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '55dd8ecb-6505-4457-94e7-0804eadf8bb9' OR (EntityID = '963BD9CD-4A10-434C-81D6-4207D2681082' AND Name = 'FirstName')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '55dd8ecb-6505-4457-94e7-0804eadf8bb9',
            '963BD9CD-4A10-434C-81D6-4207D2681082', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '963BD9CD-4A10-434C-81D6-4207D2681082'),
            'FirstName',
            'First Name',
            NULL,
            'nvarchar',
            200,
            0,
            0,
            0,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            1,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '63941229-64a7-4636-aa9b-3fb08249595a' OR (EntityID = '963BD9CD-4A10-434C-81D6-4207D2681082' AND Name = 'LastName')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '63941229-64a7-4636-aa9b-3fb08249595a',
            '963BD9CD-4A10-434C-81D6-4207D2681082', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '963BD9CD-4A10-434C-81D6-4207D2681082'),
            'LastName',
            'Last Name',
            NULL,
            'nvarchar',
            200,
            0,
            0,
            0,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            1,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '639ec8bd-8a26-42a8-b881-e5e445a3593f' OR (EntityID = '963BD9CD-4A10-434C-81D6-4207D2681082' AND Name = 'Email')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '639ec8bd-8a26-42a8-b881-e5e445a3593f',
            '963BD9CD-4A10-434C-81D6-4207D2681082', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '963BD9CD-4A10-434C-81D6-4207D2681082'),
            'Email',
            'Email',
            NULL,
            'nvarchar',
            510,
            0,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            1,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'f7dcec71-417a-4fed-8968-59626b6d177a' OR (EntityID = '963BD9CD-4A10-434C-81D6-4207D2681082' AND Name = 'JoinedAt')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'f7dcec71-417a-4fed-8968-59626b6d177a',
            '963BD9CD-4A10-434C-81D6-4207D2681082', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '963BD9CD-4A10-434C-81D6-4207D2681082'),
            'JoinedAt',
            'Joined At',
            NULL,
            'date',
            3,
            10,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'bf7dfed1-be04-4c72-84e6-dd578fff7f12' OR (EntityID = '963BD9CD-4A10-434C-81D6-4207D2681082' AND Name = 'RenewalDate')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'bf7dfed1-be04-4c72-84e6-dd578fff7f12',
            '963BD9CD-4A10-434C-81D6-4207D2681082', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '963BD9CD-4A10-434C-81D6-4207D2681082'),
            'RenewalDate',
            'Renewal Date',
            NULL,
            'date',
            3,
            10,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '2302bed3-b296-4a1f-894b-30f6297ddedd' OR (EntityID = '963BD9CD-4A10-434C-81D6-4207D2681082' AND Name = 'DuesBalance')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '2302bed3-b296-4a1f-894b-30f6297ddedd',
            '963BD9CD-4A10-434C-81D6-4207D2681082', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '963BD9CD-4A10-434C-81D6-4207D2681082'),
            'DuesBalance',
            'Dues Balance',
            'The member''s dues balance. Outside the type''s allow-list, so a participant never reads it.',
            'decimal',
            9,
            10,
            2,
            0,
            '(0)',
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '29a10c6b-faad-40a7-b588-972e9bf99463' OR (EntityID = '963BD9CD-4A10-434C-81D6-4207D2681082' AND Name = 'Status')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '29a10c6b-faad-40a7-b588-972e9bf99463',
            '963BD9CD-4A10-434C-81D6-4207D2681082', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '963BD9CD-4A10-434C-81D6-4207D2681082'),
            'Status',
            'Status',
            'Active, Lapsed or Former.',
            'nvarchar',
            40,
            0,
            0,
            0,
            'Active',
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '5d10cb83-491e-423c-abdf-5ab50297da94' OR (EntityID = '963BD9CD-4A10-434C-81D6-4207D2681082' AND Name = '__mj_CreatedAt')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '5d10cb83-491e-423c-abdf-5ab50297da94',
            '963BD9CD-4A10-434C-81D6-4207D2681082', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '963BD9CD-4A10-434C-81D6-4207D2681082'),
            '__mj_CreatedAt',
            'Created At',
            NULL,
            'datetimeoffset',
            10,
            34,
            7,
            0,
            'getutcdate()',
            0,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '9615e1e6-27ed-4b75-b4eb-2c03bc9ba9c7' OR (EntityID = '963BD9CD-4A10-434C-81D6-4207D2681082' AND Name = '__mj_UpdatedAt')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '9615e1e6-27ed-4b75-b4eb-2c03bc9ba9c7',
            '963BD9CD-4A10-434C-81D6-4207D2681082', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '963BD9CD-4A10-434C-81D6-4207D2681082'),
            '__mj_UpdatedAt',
            'Updated At',
            NULL,
            'datetimeoffset',
            10,
            34,
            7,
            0,
            'getutcdate()',
            0,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '5a9406ef-eb12-4d24-8683-63d5b365ff8f' OR (EntityID = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0' AND Name = 'ID')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '5a9406ef-eb12-4d24-8683-63d5b365ff8f',
            'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0'),
            'ID',
            'ID',
            NULL,
            'uniqueidentifier',
            16,
            0,
            0,
            0,
            'newsequentialid()',
            0,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            1,
            1,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '3a909aef-5e0b-4ad2-942a-8d38f1979035' OR (EntityID = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0' AND Name = 'Name')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '3a909aef-5e0b-4ad2-942a-8d38f1979035',
            'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0'),
            'Name',
            'Name',
            NULL,
            'nvarchar',
            400,
            0,
            0,
            0,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            1,
            1,
            0,
            1,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '90482d09-063b-47b3-a38f-1365ac1b6a74' OR (EntityID = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0' AND Name = 'Region')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '90482d09-063b-47b3-a38f-1365ac1b6a74',
            'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0'),
            'Region',
            'Region',
            'The region the chapter serves.',
            'nvarchar',
            200,
            0,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            1,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'daea2ae5-6a54-4556-b6c4-95bdd7957428' OR (EntityID = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0' AND Name = 'CharterDate')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'daea2ae5-6a54-4556-b6c4-95bdd7957428',
            'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0'),
            'CharterDate',
            'Charter Date',
            NULL,
            'date',
            3,
            10,
            0,
            1,
            NULL,
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            1,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'bbe828ef-ba0b-4f16-a9a2-5f642d8d485d' OR (EntityID = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0' AND Name = 'Status')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'bbe828ef-ba0b-4f16-a9a2-5f642d8d485d',
            'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0'),
            'Status',
            'Status',
            'Active, Dormant or Closed.',
            'nvarchar',
            40,
            0,
            0,
            0,
            'Active',
            0,
            1,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            1,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = '7b7e87d9-96d5-4e04-8e88-6f61cf104665' OR (EntityID = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0' AND Name = '__mj_CreatedAt')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            '7b7e87d9-96d5-4e04-8e88-6f61cf104665',
            'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0'),
            '__mj_CreatedAt',
            'Created At',
            NULL,
            'datetimeoffset',
            10,
            34,
            7,
            0,
            'getutcdate()',
            0,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'bd417f80-39a8-413f-87bb-a456c19e8f27' OR (EntityID = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0' AND Name = '__mj_UpdatedAt')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'bd417f80-39a8-413f-87bb-a456c19e8f27',
            'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0'),
            '__mj_UpdatedAt',
            'Updated At',
            NULL,
            'datetimeoffset',
            10,
            34,
            7,
            0,
            'getutcdate()',
            0,
            0,
            0,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* SQL text to update existing entity fields from schema */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to insert entity field value with ID 89fc2f90-20b1-476c-9ad3-d21974644b83 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('89fc2f90-20b1-476c-9ad3-d21974644b83', 'BBE828EF-BA0B-4F16-A9A2-5F642D8D485D', 1, 'Active', 'Active', GETUTCDATE(), GETUTCDATE());

/* SQL text to insert entity field value with ID 776d3fd7-0e29-40a7-bee2-b26284809650 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('776d3fd7-0e29-40a7-bee2-b26284809650', 'BBE828EF-BA0B-4F16-A9A2-5F642D8D485D', 2, 'Closed', 'Closed', GETUTCDATE(), GETUTCDATE());

/* SQL text to insert entity field value with ID ef4c2bc7-f9c0-45d9-85f8-b1afc199ad32 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('ef4c2bc7-f9c0-45d9-85f8-b1afc199ad32', 'BBE828EF-BA0B-4F16-A9A2-5F642D8D485D', 3, 'Dormant', 'Dormant', GETUTCDATE(), GETUTCDATE());

/* SQL text to update ValueListType for entity field ID BBE828EF-BA0B-4F16-A9A2-5F642D8D485D */
UPDATE [${mjSchema}].[EntityField] SET ValueListType='List' WHERE ID='BBE828EF-BA0B-4F16-A9A2-5F642D8D485D';

/* SQL text to insert entity field value with ID 90809dad-f68e-470b-abae-1f72e0b22a15 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('90809dad-f68e-470b-abae-1f72e0b22a15', '29A10C6B-FAAD-40A7-B588-972E9BF99463', 1, 'Active', 'Active', GETUTCDATE(), GETUTCDATE());

/* SQL text to insert entity field value with ID ce6dbb3d-4493-4bff-b4cd-a7684f1345c4 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('ce6dbb3d-4493-4bff-b4cd-a7684f1345c4', '29A10C6B-FAAD-40A7-B588-972E9BF99463', 2, 'Former', 'Former', GETUTCDATE(), GETUTCDATE());

/* SQL text to insert entity field value with ID 74a2118e-66ef-4028-a63f-64a933b060e3 */
INSERT INTO [${mjSchema}].[EntityFieldValue]
                                       ([ID], [EntityFieldID], [Sequence], [Value], [Code], [__mj_CreatedAt], [__mj_UpdatedAt])
                                    VALUES
                                       ('74a2118e-66ef-4028-a63f-64a933b060e3', '29A10C6B-FAAD-40A7-B588-972E9BF99463', 3, 'Lapsed', 'Lapsed', GETUTCDATE(), GETUTCDATE());

/* SQL text to update ValueListType for entity field ID 29A10C6B-FAAD-40A7-B588-972E9BF99463 */
UPDATE [${mjSchema}].[EntityField] SET ValueListType='List' WHERE ID='29A10C6B-FAAD-40A7-B588-972E9BF99463';

/* Deterministic search-flag hygiene — seed name fields */

         UPDATE [${mjSchema}].[EntityField]
         SET [IncludeInUserSearchAPI] = 1,
             [UserSearchPredicateAPI] = 'BeginsWith'
         WHERE [ID] IN (
            SELECT ranked.[ID] FROM (
               SELECT f.[ID],
                      ROW_NUMBER() OVER (
                         PARTITION BY f.[EntityID]
                         ORDER BY f.[Sequence], f.[Name]
                      ) AS rn
               FROM [${mjSchema}].[EntityField] f
               INNER JOIN [${mjSchema}].[Entity] e ON e.[ID] = f.[EntityID]
               WHERE LOWER(f.[Name]) IN ('name','title','firstname','lastname','middlename','displayname','fullname','label')
                 AND f.[AutoUpdateIncludeInUserSearchAPI] = 1
                 AND f.[IncludeInUserSearchAPI] = 0
                 AND ISNULL(f.[IsPrimaryKey], 0) = 0
                 AND ISNULL(f.[IsVirtual], 0) = 0
                 AND LOWER(f.[Type]) IN ('nvarchar','varchar','char','nchar')
                 AND ISNULL(f.[Length], 0) <> -1
                 AND e.[VirtualEntity] = 0
                 AND e.[AllowUserSearchAPI] = 1
                 AND ISNULL(e.[FullTextSearchEnabled], 0) = 0
                 AND NOT ((e.[Name] = 'Logs' OR e.[Name] LIKE '% Logs') OR (e.[Name] = 'Log' OR e.[Name] LIKE '% Log') OR (e.[Name] = 'Runs' OR e.[Name] LIKE '% Runs') OR (e.[Name] = 'Run' OR e.[Name] LIKE '% Run') OR (e.[Name] = 'Run History' OR e.[Name] LIKE '% Run History') OR (e.[Name] = 'Run Steps' OR e.[Name] LIKE '% Run Steps') OR (e.[Name] = 'Run Messages' OR e.[Name] LIKE '% Run Messages') OR (e.[Name] = 'Execution Logs' OR e.[Name] LIKE '% Execution Logs') OR (e.[Name] = 'Details' OR e.[Name] LIKE '% Details') OR (e.[Name] = 'Detail' OR e.[Name] LIKE '% Detail') OR (e.[Name] = 'Lines' OR e.[Name] LIKE '% Lines') OR (e.[Name] = 'Line' OR e.[Name] LIKE '% Line') OR (e.[Name] = 'Items' OR e.[Name] LIKE '% Items') OR (e.[Name] = 'Item' OR e.[Name] LIKE '% Item') OR (e.[Name] = 'Steps' OR e.[Name] LIKE '% Steps') OR (e.[Name] = 'Step' OR e.[Name] LIKE '% Step') OR (e.[Name] = 'Params' OR e.[Name] LIKE '% Params') OR (e.[Name] = 'Param' OR e.[Name] LIKE '% Param') OR (e.[Name] = 'Mappings' OR e.[Name] LIKE '% Mappings') OR (e.[Name] = 'Mapping' OR e.[Name] LIKE '% Mapping') OR (e.[Name] = 'Audit' OR e.[Name] LIKE 'Audit %' OR e.[Name] LIKE '% Audit' OR e.[Name] LIKE '% Audit %') OR (e.[Name] = 'Record Change' OR e.[Name] LIKE 'Record Change %' OR e.[Name] LIKE '% Record Change' OR e.[Name] LIKE '% Record Change %'))
                 AND e.[SchemaName] NOT IN ('sys','staging','dbo','${mjSchema}','${mjSchema}_BizAppsCollaboration','${mjSchema}_BizAppsCommon','${mjSchema}_BizAppsTasks')
                 AND NOT EXISTS (
               SELECT 1 FROM [${mjSchema}].[EntityField] f2
               WHERE f2.[EntityID] = e.[ID]
                 AND f2.[IncludeInUserSearchAPI] = 1
            )
            ) ranked
            WHERE ranked.rn <= 3
         );


/* Create Entity Relationship: MJ_BizApps_Collaboration_Examples: Example Chapters -> MJ_BizApps_Collaboration_Examples: Example Chapter Members (One To Many via ChapterID) */
   IF NOT EXISTS (
      SELECT 1 FROM [${mjSchema}].[EntityRelationship] WHERE [ID] = '78c64b6a-b3c9-4c4b-bd51-104115757af7'
   )
   BEGIN
      INSERT INTO [${mjSchema}].[EntityRelationship] ([ID], [EntityID], [RelatedEntityID], [RelatedEntityJoinField], [Type], [BundleInAPI], [DisplayInForm], [Sequence], [__mj_CreatedAt], [__mj_UpdatedAt])
                    VALUES ('78c64b6a-b3c9-4c4b-bd51-104115757af7', 'EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0', '963BD9CD-4A10-434C-81D6-4207D2681082', 'ChapterID', 'One To Many', 1, 1, 1, GETUTCDATE(), GETUTCDATE())
   END;

/* SQL text to sync schema info from database schemas */
EXEC [${mjSchema}].[spUpdateSchemaInfoFromDatabase] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

/* Index for Foreign Keys for ExampleChapterMember */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------
-- Index for foreign key ChapterID in table ExampleChapterMember
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IDX_AUTO_MJ_FKEY_ExampleChapterMember_ChapterID' 
    AND object_id = OBJECT_ID('[${flyway:defaultSchema}].[ExampleChapterMember]')
)
CREATE INDEX IDX_AUTO_MJ_FKEY_ExampleChapterMember_ChapterID ON [${flyway:defaultSchema}].[ExampleChapterMember] ([ChapterID]);

/* SQL text to update entity field related entity name field map for entity field ID B8DC89A8-3CC4-41AB-90B4-114721A59CCB */
EXEC [${mjSchema}].[spUpdateEntityFieldRelatedEntityNameFieldMap] @EntityFieldID='B8DC89A8-3CC4-41AB-90B4-114721A59CCB', @RelatedEntityNameFieldMap='Chapter';

/* Index for Foreign Keys for ExampleChapter */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
-- Item: Index for Foreign Keys
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------;

/* Base View SQL for MJ_BizApps_Collaboration_Examples: Example Chapters */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
-- Item: vwExampleChapters
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Collaboration_Examples: Example Chapters
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ExampleChapter
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwExampleChapters]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwExampleChapters];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwExampleChapters]
AS
SELECT
    e.*
FROM
    [${flyway:defaultSchema}].[ExampleChapter] AS e
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwExampleChapters] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Collaboration_Examples: Example Chapters */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
-- Item: Permissions for vwExampleChapters
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwExampleChapters] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Collaboration_Examples: Example Chapters */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
-- Item: spCreateExampleChapter
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ExampleChapter
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateExampleChapter]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateExampleChapter];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateExampleChapter]
    @ID uniqueidentifier = NULL,
    @Name nvarchar(200),
    @Region_Clear bit = 0,
    @Region nvarchar(100) = NULL,
    @CharterDate_Clear bit = 0,
    @CharterDate date = NULL,
    @Status nvarchar(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ExampleChapter]
            (
                [ID],
                [Name],
                [Region],
                [CharterDate],
                [Status]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @Name,
                CASE WHEN @Region_Clear = 1 THEN NULL ELSE ISNULL(@Region, NULL) END,
                CASE WHEN @CharterDate_Clear = 1 THEN NULL ELSE ISNULL(@CharterDate, NULL) END,
                ISNULL(@Status, 'Active')
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ExampleChapter]
            (
                [Name],
                [Region],
                [CharterDate],
                [Status]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @Name,
                CASE WHEN @Region_Clear = 1 THEN NULL ELSE ISNULL(@Region, NULL) END,
                CASE WHEN @CharterDate_Clear = 1 THEN NULL ELSE ISNULL(@CharterDate, NULL) END,
                ISNULL(@Status, 'Active')
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwExampleChapters] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleChapter] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Collaboration_Examples: Example Chapters */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleChapter] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Collaboration_Examples: Example Chapters */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
-- Item: spUpdateExampleChapter
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ExampleChapter
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateExampleChapter]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateExampleChapter];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateExampleChapter]
    @ID uniqueidentifier,
    @Name nvarchar(200) = NULL,
    @Region_Clear bit = 0,
    @Region nvarchar(100) = NULL,
    @CharterDate_Clear bit = 0,
    @CharterDate date = NULL,
    @Status nvarchar(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ExampleChapter]
    SET
        [Name] = ISNULL(@Name, [Name]),
        [Region] = CASE WHEN @Region_Clear = 1 THEN NULL ELSE ISNULL(@Region, [Region]) END,
        [CharterDate] = CASE WHEN @CharterDate_Clear = 1 THEN NULL ELSE ISNULL(@CharterDate, [CharterDate]) END,
        [Status] = ISNULL(@Status, [Status])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwExampleChapters] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwExampleChapters]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleChapter] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ExampleChapter table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateExampleChapter]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateExampleChapter];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateExampleChapter
ON [${flyway:defaultSchema}].[ExampleChapter]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ExampleChapter]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ExampleChapter] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Collaboration_Examples: Example Chapters */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleChapter] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Collaboration_Examples: Example Chapters */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Chapters
-- Item: spDeleteExampleChapter
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ExampleChapter
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteExampleChapter]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteExampleChapter];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteExampleChapter]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ExampleChapter]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteExampleChapter] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Collaboration_Examples: Example Chapters */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteExampleChapter] TO [cdp_Developer], [cdp_Integration];

/* Base View SQL for MJ_BizApps_Collaboration_Examples: Example Chapter Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
-- Item: vwExampleChapterMembers
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- BASE VIEW FOR ENTITY:      MJ_BizApps_Collaboration_Examples: Example Chapter Members
-----               SCHEMA:      ${flyway:defaultSchema}
-----               BASE TABLE:  ExampleChapterMember
-----               PRIMARY KEY: ID
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[vwExampleChapterMembers]', 'V') IS NOT NULL
    DROP VIEW [${flyway:defaultSchema}].[vwExampleChapterMembers];
GO

CREATE VIEW [${flyway:defaultSchema}].[vwExampleChapterMembers]
AS
SELECT
    e.*,
    mjBizAppsCollabExamplesExampleChapter_ChapterID.[Name] AS [Chapter]
FROM
    [${flyway:defaultSchema}].[ExampleChapterMember] AS e
INNER JOIN
    [${flyway:defaultSchema}].[ExampleChapter] AS mjBizAppsCollabExamplesExampleChapter_ChapterID
  ON
    [e].[ChapterID] = mjBizAppsCollabExamplesExampleChapter_ChapterID.[ID]
GO
GRANT SELECT ON [${flyway:defaultSchema}].[vwExampleChapterMembers] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* Base View Permissions SQL for MJ_BizApps_Collaboration_Examples: Example Chapter Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
-- Item: Permissions for vwExampleChapterMembers
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

GRANT SELECT ON [${flyway:defaultSchema}].[vwExampleChapterMembers] TO [cdp_UI], [cdp_Developer], [cdp_Integration];

/* spCreate SQL for MJ_BizApps_Collaboration_Examples: Example Chapter Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
-- Item: spCreateExampleChapterMember
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- CREATE PROCEDURE FOR ExampleChapterMember
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spCreateExampleChapterMember]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spCreateExampleChapterMember];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spCreateExampleChapterMember]
    @ID uniqueidentifier = NULL,
    @ChapterID uniqueidentifier,
    @FirstName nvarchar(100),
    @LastName nvarchar(100),
    @Email_Clear bit = 0,
    @Email nvarchar(255) = NULL,
    @JoinedAt_Clear bit = 0,
    @JoinedAt date = NULL,
    @RenewalDate_Clear bit = 0,
    @RenewalDate date = NULL,
    @DuesBalance decimal(10, 2) = NULL,
    @Status nvarchar(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @InsertedRow TABLE ([ID] UNIQUEIDENTIFIER)

    IF @ID IS NOT NULL
    BEGIN
        -- User provided a value, use it
        INSERT INTO [${flyway:defaultSchema}].[ExampleChapterMember]
            (
                [ID],
                [ChapterID],
                [FirstName],
                [LastName],
                [Email],
                [JoinedAt],
                [RenewalDate],
                [DuesBalance],
                [Status]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ID,
                @ChapterID,
                @FirstName,
                @LastName,
                CASE WHEN @Email_Clear = 1 THEN NULL ELSE ISNULL(@Email, NULL) END,
                CASE WHEN @JoinedAt_Clear = 1 THEN NULL ELSE ISNULL(@JoinedAt, NULL) END,
                CASE WHEN @RenewalDate_Clear = 1 THEN NULL ELSE ISNULL(@RenewalDate, NULL) END,
                ISNULL(@DuesBalance, 0),
                ISNULL(@Status, 'Active')
            )
    END
    ELSE
    BEGIN
        -- No value provided, let database use its default (e.g., NEWSEQUENTIALID())
        INSERT INTO [${flyway:defaultSchema}].[ExampleChapterMember]
            (
                [ChapterID],
                [FirstName],
                [LastName],
                [Email],
                [JoinedAt],
                [RenewalDate],
                [DuesBalance],
                [Status]
            )
        OUTPUT INSERTED.[ID] INTO @InsertedRow
        VALUES
            (
                @ChapterID,
                @FirstName,
                @LastName,
                CASE WHEN @Email_Clear = 1 THEN NULL ELSE ISNULL(@Email, NULL) END,
                CASE WHEN @JoinedAt_Clear = 1 THEN NULL ELSE ISNULL(@JoinedAt, NULL) END,
                CASE WHEN @RenewalDate_Clear = 1 THEN NULL ELSE ISNULL(@RenewalDate, NULL) END,
                ISNULL(@DuesBalance, 0),
                ISNULL(@Status, 'Active')
            )
    END
    -- return the new record from the base view, which might have some calculated fields
    SELECT * FROM [${flyway:defaultSchema}].[vwExampleChapterMembers] WHERE [ID] = (SELECT [ID] FROM @InsertedRow)
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleChapterMember] TO [cdp_Developer], [cdp_Integration];

/* spCreate Permissions for MJ_BizApps_Collaboration_Examples: Example Chapter Members */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spCreateExampleChapterMember] TO [cdp_Developer], [cdp_Integration];

/* spUpdate SQL for MJ_BizApps_Collaboration_Examples: Example Chapter Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
-- Item: spUpdateExampleChapterMember
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- UPDATE PROCEDURE FOR ExampleChapterMember
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spUpdateExampleChapterMember]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spUpdateExampleChapterMember];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spUpdateExampleChapterMember]
    @ID uniqueidentifier,
    @ChapterID uniqueidentifier = NULL,
    @FirstName nvarchar(100) = NULL,
    @LastName nvarchar(100) = NULL,
    @Email_Clear bit = 0,
    @Email nvarchar(255) = NULL,
    @JoinedAt_Clear bit = 0,
    @JoinedAt date = NULL,
    @RenewalDate_Clear bit = 0,
    @RenewalDate date = NULL,
    @DuesBalance decimal(10, 2) = NULL,
    @Status nvarchar(20) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ExampleChapterMember]
    SET
        [ChapterID] = ISNULL(@ChapterID, [ChapterID]),
        [FirstName] = ISNULL(@FirstName, [FirstName]),
        [LastName] = ISNULL(@LastName, [LastName]),
        [Email] = CASE WHEN @Email_Clear = 1 THEN NULL ELSE ISNULL(@Email, [Email]) END,
        [JoinedAt] = CASE WHEN @JoinedAt_Clear = 1 THEN NULL ELSE ISNULL(@JoinedAt, [JoinedAt]) END,
        [RenewalDate] = CASE WHEN @RenewalDate_Clear = 1 THEN NULL ELSE ISNULL(@RenewalDate, [RenewalDate]) END,
        [DuesBalance] = ISNULL(@DuesBalance, [DuesBalance]),
        [Status] = ISNULL(@Status, [Status])
    WHERE
        [ID] = @ID

    -- Check if the update was successful
    IF @@ROWCOUNT = 0
        -- Nothing was updated, return no rows, but column structure from base view intact, semantically correct this way.
        SELECT TOP 0 * FROM [${flyway:defaultSchema}].[vwExampleChapterMembers] WHERE 1=0
    ELSE
        -- Return the updated record so the caller can see the updated values and any calculated fields
        SELECT
                                        *
                                    FROM
                                        [${flyway:defaultSchema}].[vwExampleChapterMembers]
                                    WHERE
                                        [ID] = @ID
                                    
END
GO

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleChapterMember] TO [cdp_Developer], [cdp_Integration]
GO

------------------------------------------------------------
----- TRIGGER FOR __mj_UpdatedAt field for the ExampleChapterMember table
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[trgUpdateExampleChapterMember]', 'TR') IS NOT NULL
    DROP TRIGGER [${flyway:defaultSchema}].[trgUpdateExampleChapterMember];
GO
CREATE TRIGGER [${flyway:defaultSchema}].trgUpdateExampleChapterMember
ON [${flyway:defaultSchema}].[ExampleChapterMember]
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE
        [${flyway:defaultSchema}].[ExampleChapterMember]
    SET
        __mj_UpdatedAt = GETUTCDATE()
    FROM
        [${flyway:defaultSchema}].[ExampleChapterMember] AS _organicTable
    INNER JOIN
        INSERTED AS I ON
        _organicTable.[ID] = I.[ID];
END;
GO

/* spUpdate Permissions for MJ_BizApps_Collaboration_Examples: Example Chapter Members */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spUpdateExampleChapterMember] TO [cdp_Developer], [cdp_Integration];

/* spDelete SQL for MJ_BizApps_Collaboration_Examples: Example Chapter Members */
-----------------------------------------------------------------
-- SQL Code Generation
-- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
-- Item: spDeleteExampleChapterMember
--
-- This was generated by the MemberJunction CodeGen tool.
-- This file should NOT be edited by hand.
-----------------------------------------------------------------

------------------------------------------------------------
----- DELETE PROCEDURE FOR ExampleChapterMember
------------------------------------------------------------
IF OBJECT_ID('[${flyway:defaultSchema}].[spDeleteExampleChapterMember]', 'P') IS NOT NULL
    DROP PROCEDURE [${flyway:defaultSchema}].[spDeleteExampleChapterMember];
GO

CREATE PROCEDURE [${flyway:defaultSchema}].[spDeleteExampleChapterMember]
    @ID uniqueidentifier
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM
        [${flyway:defaultSchema}].[ExampleChapterMember]
    WHERE
        [ID] = @ID


    -- Check if the delete was successful
    IF @@ROWCOUNT = 0
        SELECT NULL AS [ID] -- Return NULL for all primary key fields to indicate no record was deleted
    ELSE
        SELECT @ID AS [ID] -- Return the primary key values to indicate we successfully deleted the record
END
GO
GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteExampleChapterMember] TO [cdp_Developer], [cdp_Integration];

/* spDelete Permissions for MJ_BizApps_Collaboration_Examples: Example Chapter Members */

GRANT EXECUTE ON [${flyway:defaultSchema}].[spDeleteExampleChapterMember] TO [cdp_Developer], [cdp_Integration];

/* SQL text to delete unneeded entity fields (2 scoped entities) */
EXEC [${mjSchema}].[spDeleteUnneededEntityFields] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @EntityIDs='EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0,963BD9CD-4A10-434C-81D6-4207D2681082', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to insert 1 new entity field(s) */

      IF NOT EXISTS (SELECT 1 FROM [${mjSchema}].[EntityField] WHERE ID = 'e355fadd-1cc6-48bc-ae3e-121e488e7191' OR (EntityID = '963BD9CD-4A10-434C-81D6-4207D2681082' AND Name = 'Chapter')) BEGIN
         INSERT INTO [${mjSchema}].[EntityField]
         (
            [ID],
            [EntityID],
            [Sequence],
            [Name],
            [DisplayName],
            [Description],
            [Type],
            [Length],
            [Precision],
            [Scale],
            [AllowsNull],
            [DefaultValue],
            [AutoIncrement],
            [AllowUpdateAPI],
            [IsVirtual],
            [IsComputed],
            [RelatedEntityID],
            [RelatedEntityFieldName],
            [IsNameField],
            [IncludeInUserSearchAPI],
            [IncludeRelatedEntityNameFieldInBaseView],
            [DefaultInView],
            [IsPrimaryKey],
            [IsUnique],
            [RelatedEntityDisplayType],
            [__mj_CreatedAt],
            [__mj_UpdatedAt]
         )
         VALUES
         (
            'e355fadd-1cc6-48bc-ae3e-121e488e7191',
            '963BD9CD-4A10-434C-81D6-4207D2681082', -- Entity: MJ_BizApps_Collaboration_Examples: Example Chapter Members
            (SELECT COALESCE(MAX([Sequence]), 0) + 1 FROM [${mjSchema}].[EntityField] WHERE [EntityID] = '963BD9CD-4A10-434C-81D6-4207D2681082'),
            'Chapter',
            'Chapter',
            NULL,
            'nvarchar',
            400,
            0,
            0,
            0,
            NULL,
            0,
            0,
            1,
            0,
            NULL,
            NULL,
            0,
            0,
            0,
            0,
            0,
            0,
            'Search',
            GETUTCDATE(),
            GETUTCDATE()
         )
      END;

/* SQL text to update existing entity fields from schema (2 scoped entities) */
EXEC [${mjSchema}].[spUpdateExistingEntityFieldsFromSchema] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @EntityIDs='EB8761DE-34AC-4FF2-AD83-9FE4FB171BB0,963BD9CD-4A10-434C-81D6-4207D2681082', @IncludedSchemaNames='${flyway:defaultSchema}';

/* SQL text to set default column width where needed */
EXEC [${mjSchema}].[spSetDefaultColumnWidthWhereNeeded] @ExcludedSchemaNames='sys,staging,dbo,${mjSchema}', @IncludedSchemaNames='${flyway:defaultSchema}';

